### ISSUE TITLE
run_ora_df

### ISSUE THREAD

**Issue by mcjmigdal** [saezlab/decoupler-py#101]
**Describe your question**
[documentation](https://decoupler-py.readthedocs.io/en/latest/notebooks/cell_annotation.html#Enrichment-with-Over-Representation-Analysis-(ORA)) mentions function to run Over Representation Analysis on  results of differential expression analysis (`decoupler.run_ora_df`). However, there seems to be no such function in the package?

```
help(decoupler.run_ora_df)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[153], line 1
----> 1 help(decoupler.run_ora_df)

AttributeError: module 'decoupler' has no attribute 'run_ora_df'
```

**Comment by PauBadiaM** [comment]
Hi @mcjmigdal,

Thanks for noticing this. It was a mistake in the documentation, the actual name of the function is `get_ora_df`, not `run_ora_df`. See its docs [here](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.get_ora_df.html#decoupler.get_ora_df) and an example of how to use it [here](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html#Enrichment-with-Over-Representation-Analysis-(ORA)). I've updated the docs accordingly f3bc59b48985d8aa361b78a5de2e8cac8cd031eb. 
Hope this is helpful!

**Comment by mcjmigdal** [comment]
Hi @PauBadiaM this is helpful, thank you!
