### ISSUE TITLE
Loading resources for mouse is not working

### ISSUE THREAD

**Issue by riederd** [saezlab/decoupler-py#102]
**Describe the bug**
Loading `MSigDB` for mouse is not working:

```
$ python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import decoupler as dc
>>> logging.getLogger().setLevel(1)
>>> msigdb = dc.get_resource("MSigDB", organism="mouse")
Traceback (most recent call last):
  File "/home/rieder/.conda/envs/scirpy/lib/python3.10/site-packages/decoupler/omnip.py", line 61, in _check_if_omnipath
    import omnipath as op
  File "/home/rieder/.conda/envs/scirpy/lib/python3.10/site-packages/pypath/omnipath/__init__.py", line 23, in <module>
    from pypath.share import session as _session_mod
  File "/home/rieder/.conda/envs/scirpy/lib/python3.10/site-packages/pypath/__init__.py", line 110, in <module>
    info(0)
  File "/home/rieder/.conda/envs/scirpy/lib/python3.10/site-packages/pypath/__init__.py", line 81, in info
    _session_mod.log().msg(
AttributeError: 'NoneType' object has no attribute 'msg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rieder/.conda/envs/scirpy/lib/python3.10/site-packages/decoupler/omnip.py", line 254, in get_resource
    op = _check_if_omnipath()
  File "/home/rieder/.conda/envs/scirpy/lib/python3.10/site-packages/decoupler/omnip.py", line 65, in _check_if_omnipath
    raise ImportError(
ImportError: omnipath is not installed. Please install it by: `pip install omnipath`.

```

**To Reproduce**

1. Install the following packages:

```
$ pip install --upgrade git+https://github.com/saezlab/decoupler-py.git
$ pip install --upgrade git+https://github.com/saezlab/omnipath.git
$ pip install --upgrade git+https://github.com/saezlab/pypath.git
```

2. Run the following python code:

```
import logging
import decoupler as dc
logging.getLogger().setLevel(1)
msigdb = dc.get_resource("MSigDB", organism="mouse")
```

**Expected behavior**
I'd expect `msigdb` to be downloaded.

**System**
 - OS: CentOS 7.9
 - Python 3.10
 - See above (git versions available on 2024-01-24 )

**Comment by PauBadiaM** [comment]
Hi @riederd,

Thanks for raising this issue. Unfortunately, OmniPath is currently under maintenance, @deeenes what is the status about it?

**Comment by Scheket** [comment]
Hi,
I have the same bug, due to: ImportError: cannot import name 'homology' from 'pypath.utils' and I see something in orthology:

['EnsemblOrtholog', 'EnsemblOrthology', 'HomologeneOrtholog', 'HomologeneOrthology', 'Literal', 'OmaOrtholog', 'OmaOrthology', 'OrthologBase', 'OrthologMeta', 'OrthologyManager', 'OrthologyTableKey', 'ProteinOrthology', 'Proteomes', 'PtmOrthology', 'SequenceContainer', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_const', '_log', '_logger', '_orthology_cleanup_timeloop', '_se', '_types', 'abc', 'annotations', 'biomart', 'cache_mod', 'collections', 'common', 'copy', 'curl', 'datetime', 'functools', 'get_df', 'get_dict', 'get_manager', 'homologene_input', 'imp', 'init', 'inspect', 'intera', 'iteritems', 'itertools', 'json', 'mapping', 'oma_input', 'os', 'pd', 'pickle', 'range', 're', 'session', 'settings', 'sys', 'taxonomy', 'time', 'timeloop', 'translate', 'translate_df', 'uniprot_db', 'uniprot_input', 'urls', 'xrange']

**Comment by deeenes** [comment]
Hello @riederd and @Scheket,

Apologies for showing up here so late! These issues are related to a major reorganization within `pypath`, the module that provides the orthology translation. I think with the [release](https://github.com/saezlab/pypath/releases/tag/v0.16.5) that I've just published today, it should work again. The same version should be also availble in PyPI (`pip`). And you also get better orthologous gene translation from now on, as `pypath` uses by default OMA (Orthologous Matrix) instead of the outdated NCBI HomoloGene. Let me know if you still experience issues.

Best,

Denes

**Comment by maximelepetit** [comment]
Hi @deeenes 
Thanks a lot for this great tools !! 
I want to use chicken or mouse version of Progeny, msigdb and collectri
I upgrade the latest version of decoupler , omnipath and pypath using : 
```
pip install --upgrade git+https://github.com/saezlab/decoupler-py.git
pip install --upgrade git+https://github.com/saezlab/omnipath.git
pip install --upgrade git+https://github.com/saezlab/pypath.git
```
I have the same error than @Scheket 

For chicken i run : 
`progeny = dc.get_progeny(organism='9031', top=2000)`
or 
`msigdb = dc.get_resource('MSigDB',organism='9031')`
or
`net = dc.get_collectri(organism='9031', split_complexes=False)`

For mouse i run : 
`progeny = dc.get_progeny(organism='mouse', top=2000)`
or 
`msigdb = dc.get_resource('MSigDB',organism='mouse')`


Error : 
ImportError : cannot import name 'homology' from 'pypath.utils' : 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/miniconda3/envs/decoupler/lib/python3.11/site-packages/decoupler/omnip.py:544, in translate_net(net, columns, source_organism, target_organism, id_type, unique_by, **kwargs)
    543 import pypath
--> 544 from pypath.utils import homology
    545 from pypath.share import common

ImportError: cannot import name 'homology' from 'pypath.utils' (/home/labex-cortex/miniconda3/envs/decoupler/lib/python3.11/site-packages/pypath/utils/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 msigdb = dc.get_resource('MSigDB',organism=9031)
      2 msigdb

File ~/miniconda3/envs/decoupler/lib/python3.11/site-packages/decoupler/omnip.py:229, in get_resource(name, organism, **kwargs)
    225 df = df.drop(columns=['record_id', 'uniprot', 'entity_type', 'source'])
    227 if not _is_human(organism):
--> 229     df = translate_net(
    230         df,
    231         target_organism=organism,
    232         columns='genesymbol',
    233         unique_by=None,
    234     )
    236 return df.reset_index(drop=True)

File ~/miniconda3/envs/decoupler/lib/python3.11/site-packages/decoupler/omnip.py:560, in translate_net(net, columns, source_organism, target_organism, id_type, unique_by, **kwargs)
    553         raise RuntimeError(
    554             'The installed version of pypath-omnipath is too old, '
    555             f'the oldest compatible version is {PYPATH_MIN_VERSION}.'
    556         )
    558 except Exception:
--> 560     raise ImportError(
    561         'pypath-omnipath is not installed. Please install it with: '
    562         'pip install git+https://github.com/saezlab/pypath.git'
    563     )
    565 _source_organism = taxonomy.ensure_ncbi_tax_id(source_organism)
    566 _target_organism = taxonomy.ensure_ncbi_tax_id(target_organism)

ImportError: pypath-omnipath is not installed. Please install it with: pip install git+https://github.com/saezlab/pypath.git
```

For mouse Collectri work : 
`net = dc.get_collectri(organism='mouse', split_complexes=False)`

Best.

Maxime

**Comment by maximelepetit** [comment]
Hi !!
The 

I update the latest version of decoupler , omnipath and pypath : 
omnipath : 1.0.8    
pypath-omnipath : 0.16.9
decoupler : 

I have a new error :

**Comment by deeenes** [comment]
Hi Maxime, What version of `pypath-omnipath` do you have installed?

```
import pypath
pypath.__version__
'0.16.4'
```

**Comment by maximelepetit** [comment]
hi @deeenes ,

I found the error ! 

In lib/python3.11/site-packages/, i had  pypath_omnipath-0.16.9.dist-info/ and pypath-0.1.dist-info/ repertories, remove the last one seems to fix my issue.

Sorry for the inconvenience ! 

Maxime

**Comment by deeenes** [comment]
The package in PyPI is called `pypath-omnipath`, not `pypath`, because a package with the latter name has existed since long time ago. As far as I'm aware, this latter is not a really relevant package, I doubt anyone actually uses it. The name of our module is still `pypath`.

**Comment by aalockhart1** [comment]
I am having a very similar problem. If I run `progeny = dc.get_progeny(organism='human', top=500)` I get the same result as the tutorial but if I run `progeny = dc.get_progeny(organism='mouse', top=500)` I get the same error.

```
ModuleNotFoundError                       Traceback (most recent call last)
File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:543](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:543), in translate_net(net, columns, source_organism, target_organism, id_type, unique_by, **kwargs)
    [541](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:541)     return tuple(map(int, v.split('.')))
--> [543](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:543) import pypath
    [544](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:544) from pypath.utils import homology

ModuleNotFoundError: No module named 'pypath'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[98], [line 1](vscode-notebook-cell:?execution_count=98&line=1)
----> [1](vscode-notebook-cell:?execution_count=98&line=1) progeny = dc.get_progeny(organism='mouse', top=500)
      [2](vscode-notebook-cell:?execution_count=98&line=2) progeny
...
    [563](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:563)     )
    [565](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:565) _source_organism = taxonomy.ensure_ncbi_tax_id(source_organism)
    [566](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/decoupler/omnip.py:566) _target_organism = taxonomy.ensure_ncbi_tax_id(target_organism)

ImportError: pypath-omnipath is not installed. Please install it with: pip install git+https://github.com/saezlab/pypath.git
```

pypath-omnipath version 0.16.9 is installed and I don't have pypath installed at all so that can't be the issue.
