### ISSUE TITLE
Flag for sorting of gene names

### ISSUE THREAD

**Issue by leoTiez** [saezlab/decoupler-py#103]
First of all, thanks for contributing w/ your comprehensive library to the omics community!

I've got question or rather suggestion for creating the pseudo-bulk data. I performed a cross-species analysis, and I got very surprised by the results of my PCA after using the `get_pseudobulk` method provided in your library defined here: https://github.com/saezlab/decoupler-py/blob/f3bc59b48985d8aa361b78a5de2e8cac8cd031eb/decoupler/utils_anndata.py#L290. When I dug into your code, I realised that you sort the `var` names in the AnnData object: https://github.com/saezlab/decoupler-py/blob/f3bc59b48985d8aa361b78a5de2e8cac8cd031eb/decoupler/utils_anndata.py#L118 .

I couldn't find a particular reason why this is important for the code itself (i.e. some algorithms that expects sorted gene names). And obviously that's not a bug by itself. However, for the particular case of a cross-species comparison, this can be problematic, as gene names can change (and therefore there relative order with respect to each other). Maybe a flag that can be specifically set could make your program available to an even wider community?! Let me know what you think (or how I can contribute).

**Comment by PauBadiaM** [comment]
Hi @leoTiez ,

Thank you for using it!

Regarding your question, could I get some for context on how gene names can affect the result in cross-species comparisons? `decoupler` just sorts the gene names alphabetically, but the contents inside each feature should not be affected by this. There must be something else that is affecting the PCA, maybe the grouping of the samples? Could you provide a toy example on how you call `dc.get_pseudobulk`?

**Comment by leoTiez** [comment]
Thanks @PauBadiaM for getting back in touch so quickly. Agreed that the sorting doesn't affect the content, yet when I use the pseudo-bulk matrix of different species for performing the PCA, they must correspond to the orthogolous/same gene. But since the names can change, the sorting will affect the order of dimensions, which can then differ between species. And the PCA compares the variance along these dimensions, which do not correspond anymore to the same genes.

I forgot to mention it, but I didn't use the scanpy PCA but the scikit PCA. I had a quick look right now at scanpy's implementation, and they don't seem to do much different to what I do (for example using the var names etc).

Might be overall a niche use case tho.
