### ISSUE TITLE
decoupler.plot_barplot ax

### ISSUE THREAD

**Issue by annita-louloupi** [saezlab/decoupler-py#104]
**Describe your question**
Hi! Thank you for developing this wonderful package! I have a request/question
Would it be possible to add the option of defining the ax when using dc.plot_barplot? I have noticed that some plot functions have this option and some don't. Is there a reason for it?
Thank you!

**Comment by PauBadiaM** [comment]
Hi @annita-louloupi,

I've added the argument `ax` to `dc.plot_barplot`. You can use it after installing the latest version from GitHub:
```
pip install git+https://github.com/saezlab/decoupler-py
```
Hope this is helpful!

**Comment by annita-louloupi** [comment]
Hi @PauBadiaM thank you for taking my request into consideration!
Much appreciated!
