### ISSUE TITLE
summarize_acts Error

### ISSUE THREAD

**Issue by liujilei156231** [saezlab/decoupler-py#11]
I runned

 `dc.run_gsva(mat=dc_data, net=MSigDB, source='geneset', target='genesymbol', verbose=True,use_raw=False)` 
`mean_enr = dc.summarize_acts(dc_data, groupby='leiden', min_std=1)`

But:
``` TypeError                                 Traceback (most recent call last)
Input In [45], in <cell line: 1>()
----> 1 mean_enr = dc.summarize_acts(dc_data, groupby='leiden', min_std=1)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/decoupler/utils.py:289, in summarize_acts(acts, groupby, obs, var, mode, min_std)
    287 msk = obs == groups[i]
    288 if mode == 'mean':
--> 289     summary[i] = np.mean(acts[msk], axis=0, where=np.isfinite(acts[msk]))
    290 elif mode == 'median':
    291     summary[i] = np.median(acts[msk], axis=0)

File <__array_function__ internals>:5, in mean(*args, **kwargs)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3438, in mean(a, axis, dtype, out, keepdims, where)
   3436         pass
   3437     else:
-> 3438         return mean(axis=axis, dtype=dtype, out=out, **kwargs)
   3440 return _methods._mean(a, axis=axis, dtype=dtype,
   3441                       out=out, **kwargs)

TypeError: mean() got an unexpected keyword argument 'where'```

**Comment by liujilei156231** [comment]
![image](https://user-images.githubusercontent.com/62644866/180117000-1b12a166-e8b4-4c46-b990-b91c0989b593.png)

![image](https://user-images.githubusercontent.com/62644866/180117029-46f69d7b-d2e8-45db-a631-44fdf69a990d.png)

**Comment by PauBadiaM** [comment]
Hi @liujilei156231 

Could you tell me what version of `numpy` do you have? The where argument was added in `numpy-1.17` so if you have an older version it will not work.
I will update the requirements of the package to solve this mismatch, in the meantime you can run:
```
pip install numpy==1.17
```

**Comment by PauBadiaM** [comment]
I actually modified the function so that it doesn't use the where argument anymore to make it work with older versions of numpy. Could you install the latest version of decoupler and test if it works? (You will have to restart the session)
```
pip install git+https://github.com/saezlab/decoupler-py
```

**Comment by liujilei156231** [comment]
It works now.Thanks @PauBadiaM   for this efforts!
