### ISSUE TITLE
PLOT issues

### ISSUE THREAD

**Issue by Sophon-0** [saezlab/decoupler-py#114]
Hello,

1) The ANOVA plot does not provide enough colors to differentiate the cell types. is there an option to add our own colors ? And it's even confusing with the conditions.
2) The dc.plot_network is not giving the same output as the tutorial. The whole plot is either green or dark blue, based on the gene expression log2FC, I assume. Basically, I don't see any label nor edges, I just see an ocean of green and the names of the TF and genes on it.

Thanks

**Comment by PauBadiaM** [comment]
Hi @AgentScientist,

1. ANOVA plot: you can change the `cmap_cats` to use your preferred colormap for categories, you can even pass a custom one.
2. Network plot: Depending on the `igraph` and `matplotlib` version you have the scales change completely, you can play with the `node_size` parameter to see if your nodes are either too big or too small.

Hope this is helpful!

**Comment by AgentScientist** [comment]
Thanks a lot ! The default node size was 100
