### ISSUE TITLE
dc.run_mlm only returning data for 1 source

### ISSUE THREAD

**Issue by aalockhart1** [saezlab/decoupler-py#115]
Hi,
When I run the following code: 

```
dc.run_mlm(
    mat=adata,
    net=progeny,
    source='source',
    target='target',
    weight='weight',
    verbose=True
)
```
I get the following
`2506 features of mat are empty, they will be removed.
Running mlm on mat with 308 samples and 11943 targets for 1 sources.`

The only source I get data for is JAK-STAT. Any ideas? Thanks in advance

**Comment by PauBadiaM** [comment]
Hi @aalockhart1,

It looks like you have few overlap hits between the resource progeny and non-zero genes in your mat (decoupler filters out sources with less than 5 target genes in your mat). How many `top` genes are you using when running `dc.get_progeny`? I would recommend to increase the number and see if you get better overlap but unfortunately it just seems like your data consists mostly of zeros. Hope this is helpful!

**Comment by aalockhart1** [comment]
That worked, thank you!
