### ISSUE TITLE
Is run_aucell thread-safe to run in a multi-threaded script?

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#118]
Running AUCell for multiple gene sets can be time consuming, so ideally one would like to run multiple genesets in parallel. Given the current implementation of run_aucell, is this feasible and thread-safe? Or will it only work if the input is not an AnnData object that gets modified at the end? Thanks!

**Comment by PauBadiaM** [comment]
Hi @pcm32,

The way I coded it is that we run multiple genesets in parallel already using numba, and it does not matter what the input is (AnnData or dataframe). Hope this is helpful!

**Comment by pcm32** [comment]
Thanks. Is there a way to control then the number of concurrent processes that would run should you give it various gene sets at the same time in the network? I'm assuming this is how you achieve the parallelisation, correct? Perhaps through a numba max number of processes?

**Comment by PauBadiaM** [comment]
By default it uses all available cores, but you can control the number of threads by changing this global parameter:

```python
import numba as nb
nb.set_num_threads(n=32)

# Then run decoupler functions here
```
