### ISSUE TITLE
plot_network function top target

### ISSUE THREAD

**Issue by Sophon-0** [saezlab/decoupler-py#119]
In the plot_network function, the targets to display are chosen based on their the absolute value provided in obs multiplied by their weight in net

**Comment by PauBadiaM** [comment]
Hi @Sophon-0,

Indeed, you can also manually pick which targets to plot by providing a list of target genes in `n_targets`. Also you can just select the top positive ones by setting `by_abs` to False. More information [here](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.plot_network.html#decoupler.plot_network).
