### ISSUE TITLE
Progeny pvals

### ISSUE THREAD

**Issue by nicolebussola** [saezlab/decoupler-py#122]
Hi, first of all thank you for this great tool. I was following the tutorial for footprint enrichment with PROGENy; the pvals outpupt by the mlm model are not "checked" but ideally I should consider a pathway to be active/inactive if the corresponding pvalue is significant, is that correct?

**Comment by PauBadiaM** [comment]
Hi @nicolebussola,

Thanks! Indeed, you can check if the corresponding p-value is significant to filter pathways.
