### ISSUE TITLE
Getting pval=0 for various enriched pathways after running GSEA

### ISSUE THREAD

**Issue by saksham132** [saezlab/decoupler-py#124]
Hi, I am running GSEA analysis for some single cell data. For many enriched pathways the pval = 0. The issue is I am not able to plot the result because of this 0 value, as it throws the runtime error due to (log(0)) in the calculation. I'm uncertain whether these p-values are genuinely 0 or if they represent extremely small values rounded to 0. Additionally, I might have made some error in the analysis earlier. Could you provide guidance on how to address this issue or suggest alternative plotting methods for such data? Thanks for any assistance!

code snippet:
<img width="705" alt="Screenshot 2024-05-15 at 10 01 40 AM" src="https://github.com/saezlab/decoupler-py/assets/64698707/79672487-56d5-4529-a4e5-ef2c2a249ba5">

<img width="587" alt="Screenshot 2024-05-15 at 9 53 20 AM" src="https://github.com/saezlab/decoupler-py/assets/64698707/de420f43-1ab7-428c-b9fc-36d2af8881c9">

<img width="1783" alt="Screenshot 2024-05-15 at 9 53 39 AM" src="https://github.com/saezlab/decoupler-py/assets/64698707/b281bd26-884c-4bf0-bbb2-03662674f2f5">

**Comment by PauBadiaM** [comment]
Hi @saksham132 ,

Whenever you find p-values that are 0 in `gsea` it means that none of the randomly permuted values are higher than the original statistic. To try to solve this, you can:

- increase the number of permutations (though increasing computing time)
- set them to the minimum non-zero p-value in your results
- use another enrichment method for example [`ulm`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.run_ulm.html#decoupler.run_ulm) which will be able to provide p-values

Hope this is helpful!

**Comment by saksham132** [comment]
Thank you for the suggestions! I will try implementing these.
