### ISSUE TITLE
ORA analysis get hung in jupyter notebook

### ISSUE THREAD

**Issue by zhaleh-safikhani** [saezlab/decoupler-py#126]
Hi @PauBadiaM, For some reasom when I run some functions from decoupler like ora in jupyter notebook, they got hung while they work fine in a python script. I use the same virtual environment in both cases and I have decoupler=1.6.0 installed in this env. Do you have any idea why that might be the case?

**Comment by PauBadiaM** [comment]
Hi @zhaleh-safikhani ,

Did you run it using the verbose parameter, could you tell me exactly where does it get stuck?
It might be a problem of parallelization in case you are running decoupler on massive amounts of cpus, you could try to limit them by running these lines:
```python
import numba as nb
nb.set_num_threads(n=32)

# Then run decoupler functions here
```
