### ISSUE TITLE
matplotlib.cm.get_cmap is removed from version 3.9

### ISSUE THREAD

**Issue by zhaleh-safikhani** [saezlab/decoupler-py#127]
matplotlib.cm.get_cmap is used in marsilea to get color map and you call it in plot_associations.
so now I get this error: module 'matplotlib.cm' has no attribute 'get_cmap'
For reference 
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html

**Comment by PauBadiaM** [comment]
Hi @zhaleh-safikhani ,

Thanks for the heads up! I've checked and this new version seems to still be unstable (I cannot seem to make `matplotlib.cm.ColormapRegistry.get_cmap` work) so I'll wait until they solve their issues. For the time being, keep matplotlib version to anything below `3.9.0`.
