### ISSUE TITLE
numba version 0.60.0

### ISSUE THREAD

**Issue by Intron7** [saezlab/decoupler-py#135]
decoupler fails to import with numba version 0.60.0

https://github.com/scverse/rapids_singlecell/actions/runs/9552426465/job/26329883508

**Comment by deeenes** [comment]
See also #134

**Comment by Intron7** [comment]
I only checked issues sorry. But it seems there are some more things broken.

**Comment by deeenes** [comment]
Thanks @Intron7, Now we merged the PR above, and because `numba` won't support `numpy 2.0` until Sept the earliest, we just had to pin `numpy < 2.0`. With that, everything should work like before.

**Comment by Zethson** [comment]
@deeenes could we get a release, please?

**Comment by deeenes** [comment]
Yes, @PauBadiaM are you doing a release tomorrow? Also, we have an [old version in bioconda](https://anaconda.org/bioconda/decoupler)

**Comment by PauBadiaM** [comment]
@Zethson @Intron7 I've released the latest version with the fix: https://pypi.org/project/decoupler/1.7.0/
@deeenes the upadted version can be found in [conda-forge](https://anaconda.org/conda-forge/decoupler-py)(this new version still needs to propagate) instead of bioconda
