### ISSUE TITLE
module 'decoupler' has no attribute 'plot_network'

### ISSUE THREAD

**Issue by linanzhang** [saezlab/decoupler-py#137]
Hello,

I follow [this vignette](https://decoupler-py.readthedocs.io/en/latest/notebooks/dorothea.html) to run decoupler, and receive the following error message when running the last line:

```
dc.plot_network(
    net=net,
    n_sources=['PAX5'],
    n_targets=15,
    node_size=100,
    s_cmap='white',
    t_cmap='white',
    c_pos_w='darkgreen',
    c_neg_w='darkred',
    figsize=(5, 5)
)
```

```
AttributeError: module 'decoupler' has no attribute 'plot_network'
```
The session information is:
```
Click to view session information
-----
anndata             0.10.2
decoupler           1.5.0
matplotlib          3.8.0
numpy               1.23.4
pandas              2.1.1
scanpy              1.9.5
scipy               1.11.3
seaborn             0.12.2
session_info        1.0.0
-----
Click to view modules imported as dependencies
-----
IPython             8.15.0
jupyter_client      7.4.9
jupyter_core        5.3.0
notebook            6.5.4
-----
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
Windows-10-10.0.22631-SP0
-----
Session information updated at 2024-06-25 10:33
```

Thank you.

**Comment by PauBadiaM** [comment]
Hi @linanzhang,

It looks like you have `decoupler 1.5.0` installed but the `dc.plot_network` function was added in `decoupler 1.6.0`. You can install it either using pip:
```
pip install decoupler==1.6.0
```
or conda/mamba:
```
mamba install conda-forge::decoupler-py==1.6.0
```

In case it is useful in the future, you can always check the [release notes](https://decoupler-py.readthedocs.io/en/latest/release_notes.html) to see when a function was added or changed in each version.
Hope this is helpful!
