### ISSUE TITLE
https://omnipathdb.org/ is down hence produces error when trying to use decoupler

### ISSUE THREAD

**Issue by tomthomas3000** [saezlab/decoupler-py#14]
**https://omnipathdb.org/ is down hence produces error when trying to use decoupler. I saw from another post (https://github.com/saezlab/pypath/issues/143), that your team were able to restart. Any chance you might be able to do so again? Thank you.**

**Comment by PauBadiaM** [comment]
Hi @tomthomas3000,

Thanks for checking out the package! Recently we got a large increase of users and the server must be busy. We will let you know once it is up again. @deeenes could you take a look?

**Comment by PauBadiaM** [comment]
Hi @tomthomas3000 

It was a transient error due to memory issues in the server, should be fixed now. Feel free to open this issue again in case it doesn't work.
