### ISSUE TITLE
Warnings about annotations raised when running `dc.plot_targets`

### ISSUE THREAD

**Issue by Fantasque68** [saezlab/decoupler-py#140]
**Describe the bug**
While running codes as tutorial "pseudobulk functional analysis", the function `dc.plot_targets` raised dozens of warnings, namely `WARNING:matplotlib.text:posx and posy should be finite values`, and there isn't any gene symbol annotations on the plot.

**To Reproduce**
All the following steps and parameters are same as the tutorial, except that I used my own data.
1. `progeny = dc.get_progeny(...)`
2. `pathway_acts, pathway_pvals = dc.run_mlm(...)`
3. `dc.plot_targets(...)`

**Expected behavior**
Output dotplots with gene symbol annotations as the tutorial.

**System**
 - OS: Ubuntu 24.04
 - Python version 3.9.19
 - Versions of libraries involved 
     ```python
    pip list
    
    adjustText          1.2.0
    anndata             0.10.7
    decoupler           1.7.0
    marsilea            0.4.1
    matplotlib          3.9.0
    matplotlib-inline   0.1.7
    scanpy              1.10.1
    scikit-learn        1.5.0
    scikit-misc         0.3.1
    scipy               1.13.1
    seaborn             0.13.2
    ```

**Additional context**
N.A.

**Comment by PauBadiaM** [comment]
Hi @Fantasque68,

Huh interesting, I reproduced the same environment and it worked fined in my case. Could it be that you have `nan`s in your gene symbols, or in your t-values/log2FCs?
