### ISSUE TITLE
Dataloading

### ISSUE THREAD

**Issue by Intron7** [saezlab/decoupler-py#142]
Within `_pre.extract` you don't support `layer` and `use_raw` is set to true by default. I would suggest to add support with `_get_obs_rep` from scanpy (it's small codeblock that you can just copy). I would also argue that its better to set `use_raw` to `None` and default to `True` when raw is present and not to throw an error. I also found some other small [optimizations](https://github.com/scverse/rapids_singlecell/blob/update-decoupler/src/rapids_singlecell/decoupler_gpu/_pre.py). I could upstream those if you want it

**Comment by PauBadiaM** [comment]
Hi @Intron7,

All of this sounds good! Would you mind opening a PR? :pray:
