### ISSUE TITLE
error on importing progeny for mouse

### ISSUE THREAD

**Issue by ojikj2019** [saezlab/decoupler-py#148]
**Describe your question**
Hello,

I have been getting an error message, 'object of type 'NoneType' has no len()', when I am trying to import PROGENy model for mouse with the following string; dc.get_progeny(organism = 'Mus musculus'). Could you please let me know how I can solve this problem? Please find a Tracback and a version of packages below.

Best,

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[25], line 1
----> 1 test_mouse_progeny = dc.get_progeny(organism = 'Mus musculus')
      3 test_mouse_progeny

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/decoupler/omnip.py:250, in get_progeny(organism, top, genesymbol_resource, **kwargs)
    248 p = p.drop('record_id', axis=1)
    249 p.columns.name = None
--> 250 p = _annotation_identifiers(p, organism, genesymbol_resource)
    251 p = p[['pathway', 'genesymbol', 'weight', 'p_value']]
    252 p = p[~p.duplicated(['pathway', 'genesymbol'])]

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/decoupler/omnip.py:919, in _annotation_identifiers(net, organism, genesymbol_resource)
    906 def _annotation_identifiers(
    907         net: pd.DataFrame,
    908         organism: str | int,
   (...)
    914         ) = None,
    915         ) -> pd.DataFrame:
    917     if not _is_human(organism):
--> 919         net = translate_net(
    920             net,
    921             columns='uniprot',
    922             id_type='uniprot',
    923             source_organism=9606,
    924             target_organism=organism,
    925         )
    927     if genesymbol_resource is False:
    929         net['genesymbol'] = net['uniprot']

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/decoupler/omnip.py:732, in translate_net(net, columns, source_organism, target_organism, id_type, unique_by, **kwargs)
    729     return net
    731 _check_if_pypath()
--> 732 from pypath.utils import orthology
    733 from pypath.share import common
    734 from pypath.utils import taxonomy

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/utils/orthology.py:45
     42 import timeloop
     43 import pandas as pd
---> 45 import pypath.utils.mapping as mapping
     46 import pypath.share.common as common
     47 import pypath_common._constants as _const

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/utils/mapping.py:65
     63 import pypath_common._constants as _const
     64 import pypath.share.cache as cache_mod
---> 65 import pypath.internals.maps as maps
     66 import pypath.resources.urls as urls
     67 import pypath.share.curl as curl

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/internals/maps.py:24
     22 import pypath.share.common as common
     23 import pypath_common._constants as _const
---> 24 import pypath.internals.input_formats as input_formats
     26 __all__ = ['uniprot', 'mirbase', 'basic']
     29 uniprot = {
     30     ('embl', 'uniprot'):
     31         input_formats.UniprotMapping(
   (...)
     75         ),
     76 }

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/internals/input_formats.py:651
    643         self.attrs = (
    644             self.biomart_id_type_a,
    645             self.biomart_id_type_b,
    646         )
    648         self.biomart_mapping = BIOMART_MAPPING
--> 651 class UnichemMapping(MappingInput):
    653     _resource_id_types = {
    654         id_type: id_type
    655         for id_type in unichem_input.unichem_sources().values()
    656     }
    658     def __init__(
    659             self,
    660             id_type_a,
    661             id_type_b,
    662             ncbi_tax_id = _const.NOT_ORGANISM_SPECIFIC,
    663         ):

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/internals/input_formats.py:655, in UnichemMapping()
    651 class UnichemMapping(MappingInput):
    653     _resource_id_types = {
    654         id_type: id_type
--> 655         for id_type in unichem_input.unichem_sources().values()
    656     }
    658     def __init__(
    659             self,
    660             id_type_a,
    661             id_type_b,
    662             ncbi_tax_id = _const.NOT_ORGANISM_SPECIFIC,
    663         ):
    664         """
    665         Paramaters for UniChem based ID translation.
    666 
   (...)
    671                 Custom name for the other ID type.
    672         """

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/inputs/unichem.py:98, in unichem_sources()
     82 def unichem_sources():
     83     """
     84     ID type numeric codes and labels in UniChem. For more information see
     85     `unichem_info`.
   (...)
     89             as values.
     90     """
     93     return dict(
     94         (
     95             s.number,
     96             s.label,
     97         )
---> 98         for s in unichem_info()
     99     )

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/pypath/inputs/unichem.py:59, in unichem_info()
     57 url = urls.urls['unichem']['sources']
     58 c = curl.Curl(url, large = False, silent = False)
---> 59 soup = bs4.BeautifulSoup(c.result, 'html.parser')
     60 result = []
     62 for table in soup.find_all('table'):

File ~/anaconda3/envs/test_decoupler/lib/python3.11/site-packages/bs4/__init__.py:315, in BeautifulSoup.__init__(self, markup, features, builder, parse_only, from_encoding, exclude_encodings, element_classes, **kwargs)
    313 if hasattr(markup, 'read'):        # It's a file-type object.
    314     markup = markup.read()
--> 315 elif len(markup) <= 256 and (
    316         (isinstance(markup, bytes) and not b'<' in markup)
    317         or (isinstance(markup, str) and not '<' in markup)
    318 ):
    319     # Issue warnings for a couple beginner problems
    320     # involving passing non-markup to Beautiful Soup.
    321     # Beautiful Soup will still parse the input as markup,
    322     # since that is sometimes the intended behavior.
    323     if not self._markup_is_url(markup):
    324         self._markup_resembles_filename(markup)                

TypeError: object of type 'NoneType' has no len()

------------------------------------------------------------------------------------------------------
# packages in environment at ~/anaconda3/envs/test_decoupler:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
adjusttext                0.8                      pypi_0    pypi
anndata                   0.10.6             pyhd8ed1ab_0    conda-forge
annotated-types           0.6.0                    pypi_0    pypi
arpack                    3.8.0           nompi_h0baa96a_101    conda-forge
array-api-compat          1.5.1              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0                   pypi_0    pypi
bcrypt                    4.1.3                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
boltons                   24.0.0                   pypi_0    pypi
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.27.0               hd590300_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cattrs                    23.2.3                   pypi_0    pypi
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py311h9547e67_0    conda-forge
cryptography              42.0.8                   pypi_0    pypi
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.1           py311hb755f60_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
decoupler                 1.8.0                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
face                      20.1.1                   pypi_0    pypi
fonttools                 4.50.0          py311h459d7ec_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
future                    0.18.3                   pypi_0    pypi
get-annotations           0.1.2              pyhd8ed1ab_0    conda-forge
glom                      23.5.0                   pypi_0    pypi
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
gprofiler-official        1.0.0                    pypi_0    pypi
gtfparse                  2.5.0                    pypi_0    pypi
h5py                      3.10.0          nompi_py311hebc2b07_101    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                      pypi_0    pypi
igraph                    0.10.10              h153f77b_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
inflect                   7.0.0                    pypi_0    pypi
ipykernel                 6.25.0          py311h92b7b1e_0  
ipython                   8.22.2             pyh707e725_0    conda-forge
ipywidgets                8.1.3              pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py311h38be061_0    conda-forge
jupyterlab_widgets        3.0.11             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py311h9547e67_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
legendkit                 0.3.4                    pypi_0    pypi
leidenalg                 0.10.2          py311hb755f60_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   8.6.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libleidenalg              0.11.1               h00ab1b0_0    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.6               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.43.0                   pypi_0    pypi
loompy                    3.0.7                    pypi_0    pypi
lxml                      5.2.2                    pypi_0    pypi
marsilea                  0.3.2                    pypi_0    pypi
matplotlib-base           3.8.3           py311h54ef318_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4.20240210         h59595ed_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.4          py311h64a7726_0    conda-forge
numpy-groupies            0.10.2                   pypi_0    pypi
omnipath                  1.0.8                    pypi_0    pypi
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openpyxl                  3.1.3                    pypi_0    pypi
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2                    pypi_0    pypi
paramiko                  3.4.0                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.2.0          py311ha6c5da5_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
polars                    0.20.8                   pypi_0    pypi
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.8           py311h459d7ec_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.2                   pypi_0    pypi
pybiomart                 0.2.0                    pypi_0    pypi
pycomplexheatmap          1.6.4                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycurl                    7.45.3                   pypi_0    pypi
pydantic                  2.5.3                    pypi_0    pypi
pydantic-core             2.14.6                   pypi_0    pypi
pydeseq2                  0.4.4                    pypi_0    pypi
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0                    pypi_0    pypi
pynndescent               0.5.11             pyhca7485f_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pypath-common             0.2.2                    pypi_0    pypi
pypath-omnipath           0.16.5                   pypi_0    pypi
pyreadr                   0.5.0                    pypi_0    pypi
pysftp                    0.2.9                    pypi_0    pypi
python                    3.11.8          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-igraph             0.11.4          py311hce45d13_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2          py311h34ded2d_0    conda-forge
rdata                     0.11.2                   pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
requests-cache            1.1.1                    pypi_0    pypi
scanpy                    1.9.8              pyhd8ed1ab_0    conda-forge
scikit-learn              1.4.1.post1     py311hc009520_0    conda-forge
scipy                     1.12.0          py311h64a7726_2    conda-forge
seaborn                   0.13.2               hd8ed1ab_0    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_0    conda-forge
session-info              1.0.0              pyhd8ed1ab_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.5                      pypi_0    pypi
sqlparse                  0.5.0                    pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.1          py311h1f0f07a_0    conda-forge
stdlib-list               0.10.0             pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.11.0            h00ab1b0_1    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.4.0              pyhc1e730c_0    conda-forge
timeloop                  1.0.2                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml                      0.10.2                   pypi_0    pypi
tornado                   6.4             py311h459d7ec_0    conda-forge
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.2             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024a                h0c530f3_0    conda-forge
umap-learn                0.5.5           py311h38be061_1    conda-forge
url-normalize             1.4.3                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.11             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0                   pypi_0    pypi
xarray                    2024.5.0                 pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zeromq                    4.3.5                h59595ed_1    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge

**Comment by deeenes** [comment]
Hello, it's looks like an old issue in `pypath`, can you pls update it and try again?

```
pip install --upgrade pypath-omnipath
```

**Comment by ojikj2019** [comment]
> Hello, it looks like an old issue in `pypath`, can you pls update it and try again?
> 
> ```
> pip install --upgrade pypath-omnipath
> ```
