### ISSUE TITLE
Equivalent of filtering for genes that have at least 1 RPM?

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [saezlab/decoupler-py#152]
**Describe your question**

Quick question, but I'd lik to ask if this:

`genes = dc.filter_by_expr(adata,lib_size=1e6, min_count=1)`

considering the default values of the function, would be equivalent of doing a filtering for genes that have at least 1 RPM for bulk RNA-seq? Or do you have another function that is more appropriate for this type of filtering (considering the default params)? I'm assuming from reading the docstring of that function that the lib_size is respective of the normalization process that was done before passing the adata to that filter_by_expr, correct?

The adata.X in this case would be the counts lognormalized using scanpy (normalize_total with 10e6, same as the lib_Size of the decoupler function, and log1p with the default values that scanpy uses)

Thank you! :)

**Comment by PauBadiaM** [comment]
Hi @Rafael-Silva-Oliveira,

Sorry for the delayed reply, I was on holidays. Yes but be careful, the function `dc.filter_by_expr` expects an `AnnData` object with raw integer counts, not already normalized counts. The `lib_size` parameter is independent of the normalization used afterwards, you can set it to the same value if desired. Let me know if you have further questions.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> Sorry for the delayed reply, I was on holidays. Yes but be careful, the function `dc.filter_by_expr` expects an `AnnData` object with raw integer counts, not already normalized counts. The `lib_size` parameter is independent of the normalization used afterwards, you can set it to the same value if desired. Let me know if you have further questions.

Awesome, thank you very much! I'll have that in mind and perform that filtering using just the raw counts to 10e6 and then apply the normalization afterwards to filter only those genes > 1 RPM :) Thank you!
