### ISSUE TITLE
Version Incompatibility Between decoupler and pypath-omnipath (ImportError: Requires pypath-omnipath >= 0.14.28

### ISSUE THREAD

**Issue by victorsanchezarevalo** [saezlab/decoupler-py#157]
### **Describe the bug**
When running `decoupler` to infer transcription factor activities using `dc.run_ulm` and pathway activities using `dc.run_mlm`, I encounter an incompatibility issue with `pypath-omnipath`. The error message is:

```
ImportError: The installed version of pypath-omnipath is too old, the oldest compatible version is 0.14.28.
```

Even after updating to the latest version of `pypath-omnipath` (1.0.8), this error persists. The problem occurs in two specific sections of my code:

1. **Transcription factor activities**:
   ```python
   # Infer TF activities with ulm
   tf_acts, tf_pvals = dc.run_ulm(mat=mat, net=collectri, verbose=True)
   tf_acts
   ```

2. **Pathway activities**:
   ```python
   # Infer pathway activities with mlm
   pathway_acts, pathway_pvals = dc.run_mlm(mat=mat, net=progeny, verbose=True)
   pathway_acts
   ```

In both cases, the code fails due to the version incompatibility between `decoupler` and `pypath-omnipath`.

### **To Reproduce**

1. Set up a clean Python environment and install the latest versions of `decoupler` and `pypath-omnipath`:
   ```bash
   pip install decoupler
   pip install pypath-omnipath
   ```

2. Run the following code for transcription factor activities:
   ```python
   # Infer TF activities with ulm
   tf_acts, tf_pvals = dc.run_ulm(mat=mat, net=collectri, verbose=True)
   tf_acts
   ```

3. Run the following code for pathway activities:
   ```python
   # Infer pathway activities with mlm
   pathway_acts, pathway_pvals = dc.run_mlm(mat=mat, net=progeny, verbose=True)
   pathway_acts
   ```

4. Observe the error:
   ```
   ImportError: The installed version of pypath-omnipath is too old, the oldest compatible version is 0.14.28.
   ```

### **Expected behavior**
I expect the version of `pypath-omnipath` to be compatible with `decoupler`, allowing both transcription factor and pathway activity inference to run without any import errors.

### **System**
- OS: Fedora 41
- Python version: 3.12 (Miniforge3)
- Versions of libraries involved:
  - `decoupler`: Latest (installed from PyPI)
  - `pypath-omnipath`: 1.0.8 (latest available)
  - `omnipath`: 1.0.8

### **Additional context**
The error arises specifically in the functions `dc.run_ulm` and `dc.run_mlm`, which infer transcription factor activities and pathway activities, respectively, using a gene expression matrix (`mat`) and regulatory or pathway networks (`collectri` and `progeny`). I've attempted uninstalling and reinstalling the packages, but the error persists. The issue seems to be a mismatch between the expected version of `pypath-omnipath` and the version currently installed.

**Comment by PauBadiaM** [comment]
Hi @victorsanchezarevalo,

Mhm, something is wrong here, I cannot reproduce your error. One thing, `pypath-omnipath` latest version is `0.16.17` not `1.0.8`, that is for `omnipath`, another package. Also, the enrichment methods do not make any call to `omnipath` once the net is loaded so the error should not be triggered there. Are you using the non-human version of any of the resources? Then you need to install the appropriate version for `pypath-omnipath`.
