### ISSUE TITLE
Data Decompression Error (-3) While Fetching PROGENy Model Weights in Decoupler

### ISSUE THREAD

**Issue by victorsanchezarevalo** [saezlab/decoupler-py#159]
Aquí tienes un ejemplo estructurado de cómo escribir un informe del error que estás experimentando:

---

**Title**: Error while running `get_progeny`: Invalid block type during data decompression

**Describe the bug**  
When I try to retrieve the PROGENy model weights using `dc.get_progeny` in `Decoupler`, I encounter an error related to data decompression. The error indicates an invalid block type while decompressing data from the PROGENy resource.

**Error**:
```plaintext
Downloading annotations for all proteins from the following resources: `['PROGENy']`
Downloading data from `https://omnipathdb.org/annotations?format=tsv&resources=PROGENy`
39.0MB [00:01, 31.4MB/s]
Traceback (most recent call last):
  ...
error: Error -3 while decompressing data: invalid block type
```

**To Reproduce**  
1. Install `decoupler` in a clean Python environment.
2. Use the following code to try to retrieve PROGENy model weights:
   ```python
   import decoupler as dc
   progeny = dc.get_progeny(top=500, organism='mouse')
   ```
3. The error occurs during the download of data from the Omnipath PROGENy resource.

**Expected behavior**  
I expect to successfully download and retrieve the PROGENy model weights for the mouse organism without encountering any data decompression errors.

**System**  
- **OS**: Fedora 40
- **Python version**: 3.10
- **Other libraries**: Omnipath

**Additional context**  
The issue seems to occur during the decompression of data downloaded from the Omnipath database. I have also attempted to clear the cache using the following Python code, but the issue persists:
```python
import os
os.system('rm -rf ~/.cache/omnipathdb/*')
```

**Comment by deeenes** [comment]
Hola, See my answer [here](https://github.com/saezlab/pypath/issues/290#issuecomment-2425165866), probably your traceback is the same. If this doesn't fix the issue, please post a full traceback.

**Comment by victorsanchezarevalo** [comment]
Hi, I still have the same problem:

%runcell -n '[13] Pathway activities with mlm' /home/vjsanchez/Documentos/Mis_analisis/Ester_Martin/12_decoupler.py
Downloading annotations for all proteins from the following resources: `['PROGENy']`
Downloading data from `https://omnipathdb.org/annotations?format=tsv&resources=PROGENy`
Retrying (Retry(total=2, connect=None, read=None, redirect=5, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)'))': /annotations?format=tsv&resources=PROGENy
39.0MB [00:03, 11.8MB/s]
Traceback (most recent call last):

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/spyder_kernels/customize/utils.py:209 in exec_encapsulate_locals
    exec_fun(compile(code_ast, filename, "exec"), globals)

  File ~/Documentos/Mis_analisis/Ester_Martin/12_decoupler.py:287
    progeny = dc.get_progeny(top=500, organism='mouse')

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/decoupler/omnip.py:250 in get_progeny
    p = _annotation_identifiers(p, organism, genesymbol_resource)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/decoupler/omnip.py:919 in _annotation_identifiers
    net = translate_net(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/decoupler/omnip.py:758 in translate_net
    hom_net = orthology.translate_df(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:2262 in translate_df
    return manager.translate_df(**args, **kwargs)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:620 in translate_df
    ortho_df = self.get_df(**args)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:515 in get_df
    table = self.which_table(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:233 in which_table
    self.load(key)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:242 in load
    self.tables[key] = globals()[f'{key.resource.capitalize()}Orthology'](

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:1492 in __init__
    ProteinOrthology.__init__(**locals())

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:869 in __init__
    self.load()

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/orthology.py:1506 in load
    oma_data = oma_input.oma_orthologs(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/inputs/oma.py:125 in oma_orthologs
    a, b = (

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/inputs/oma.py:139 in <genexpr>
    for id_ in _id_translate(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/inputs/oma.py:244 in _id_translate
    uniprots = mapping.map_name(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:3551 in map_name
    return mapper.map_name(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath_common/_misc.py:2953 in wrapper
    return func(*args, **kwargs)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:2193 in map_name
    mapped_names = self.uniprot_cleanup(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:2227 in uniprot_cleanup
    uniprots = self.trembl_swissprot(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:2868 in trembl_swissprot
    genesymbols = self.map_name(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath_common/_misc.py:2953 in wrapper
    return func(*args, **kwargs)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:1978 in map_name
    mapped_names = self._map_name(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:2510 in _map_name
    tbl = self.which_table(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:1562 in which_table
    self.load_mapping(

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:3208 in load_mapping
    reader = MapReader(param = resource, **kwargs)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:258 in __init__
    self.load()

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:288 in load
    self.read()

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:450 in read
    getattr(self, method)()

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/utils/mapping.py:893 in read_mapping_uniprot
    data = query.perform()

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/inputs/uniprot.py:681 in perform
    _id, *variables = zip(*self)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/inputs/uniprot.py:656 in __iter__
    _ = next(result)

  File ~/miniforge3/envs/decoupler/lib/python3.10/site-packages/pypath/share/curl.py:766 in iterfile
    for line in fileobj:

  File ~/miniforge3/envs/decoupler/lib/python3.10/gzip.py:314 in read1
    return self._buffer.read1(size)

  File ~/miniforge3/envs/decoupler/lib/python3.10/_compression.py:68 in readinto
    data = self.read(len(byte_view))

  File ~/miniforge3/envs/decoupler/lib/python3.10/gzip.py:500 in read
    uncompress = self._decompressor.decompress(buf, size)

error: Error -3 while decompressing data: invalid block type

**Comment by deeenes** [comment]
Here we see that even retrieving this relatively small query from our server failed once, and succeeded only after a retry:

```
Downloading data from https://omnipathdb.org/annotations?format=tsv&resources=PROGENy
Retrying (Retry(total=2, connect=None, read=None, redirect=5, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)'))': /annotations?format=tsv&resources=PROGENy
```

This error suggests networking issues, such as timeout, high latency, or many lost packets.

The subsequent error is similarly from a network transaction, this case to uniprot.org.

To address the error, it is important to remove the corrupted item from pypath's cache, as [shown here](https://github.com/saezlab/pypath/issues/290#issuecomment-2425165866). Also, more information about the error is available in pypath's log.

It might make sense to try from a different network connection.

**Comment by victorsanchezarevalo** [comment]
It works fine with the human dataset, but the error occurs only with the mouse dataset. I have removed the corrupted file, but the error persists.
