### ISSUE TITLE
docker image missing omnipath module

### ISSUE THREAD

**Issue by sgaGT** [saezlab/decoupler-py#161]
Dear decoupler developers, thank you for your work.

**Describe the bug**

I need to run decoupler within a container, so I pulled the docker image that you provided. Unfortunately, omnipath seems not be available in the container. When get_collectri() is  called, the code breaks. 
Could you please include omnipath in the docker image?

**To Reproduce**

singularity pull docker://ghcr.io/saezlab/publish-packages/decoupler:sha-5838309
mv decoupler_sha-5838309.sif decoupler.sif
singularity shell --no-home decoupler.sif

Singularity> python3
>>> import omnipath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'omnipath'

**System**
 - OS: ubuntu 22.04
 - Python version 3.11.7

**Additional context**

My analysis are on scRNAseq data from mouse tissue, so I was using:
 
import decoupler as dc
from anndata import read_h5ad

fmd = read_h5ad("fmd_annotated_SingleR.h5ad")
net = dc.get_collectri(organism='mouse', split_complexes=False)
TF_consensus = dc.decouple(
    fmd,
    net=net,
    min_n=5,
    use_raw=False,
    verbose=True
)
TF_consensus.write_h5ad("fmd_TF_consensus.h5ad")

Thank you for your help,
Best

**Comment by deeenes** [comment]
Hi @sgaGT,

Indeed `omnipath` is an optional dependency, and not part of the image created by Anaconda. I've just updated the package dependencies to define extras, and the Dockerfile to install all those extras. 

@PauBadiaM, shall we update the image distributed by ghcr.io, and the PyPI package? You have access right for those.

We also have the [saezverse](https://github.com/saezlab/saezverse) Docker image, where all our tools are installed. 

Best,
Denes
