### ISSUE TITLE
Differences between wmean and wsum methods

### ISSUE THREAD

**Issue by frankligy** [saezlab/decoupler-py#20]
**Describe your question**
Hello, thanks a lot for developing this awesome package, I was wondering if I can inquire what the differences are between the implementations of `wmeans` and `wsum`, because their docstring seems to be the same. Thanks so much in advance!

`wmeans`
```
    Weighted sum (WMEAN).
    WMEAN infers regulator activities by first multiplying each target feature by its associated weight which then are summed
    to an enrichment score (`wmean_estimate`). Furthermore, permutations of random target features can be performed to obtain a
    null distribution that can be used to compute a z-score (`wmean_norm`), or a corrected estimate (`wmean_corr`) by
    multiplying `wmean_estimate` by the minus log10 of the obtained empirical p-value.
```

`wsum`
```
    Weighted sum (WSUM).
    WSUM infers regulator activities by first multiplying each target feature by its associated weight which then are summed
    to an enrichment score (`wsum_estimate`). Furthermore, permutations of random target features can be performed to obtain a
    null distribution that can be used to compute a z-score (`wsum_norm`), or a corrected estimate (`wsum_corr`) by multiplying
    `wsum_estimate` by the minus log10 of the obtained empirical p-value.
```

**Comment by PauBadiaM** [comment]
Hi @frankligy 

Thanks for checking out the package! Indeed there was an error in the documentation, I've just updated it. Both methods are very similar, their difference is that one computes the weighted sum, meaning that we multiply the gene expression of each target gene with the associated weight in prior knowledge the network, while in the weighted mean we first compute the weighted sum and then we divide that number by the absolute sum of the weights for that regulon, thus obtaining a "mean". 

Hope this is clear! If you have more questions feel free to ask.

**Comment by frankligy** [comment]
Thanks so much for the prompt explanation! I really appreciate it!
