### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by joseph-siefert** [saezlab/decoupler-py#22]
Thanks for the great tool. I'm running into an SSL error when trying to query progeny:

`
progeny = dc.get_progeny(top=300)
`

Gives:
`SSLError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?format=tsv&resources=PROGENy (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))`

Any idea how to fix this?

**Comment by deeenes** [comment]
Hi Joseph,

PROGENy and other database knowledge is accessed by decoupler from OmniPath (omnipathdb.org), a server maintained by our group. The certificate of our server is valid and is signed by the *R3* certificate, which is then signed by the *ISGR Root X1* root certificate. All certificates are provided by our server, but the *ISGR Root X1* should be also available from your operating system or other software running on it. More information is available here: https://www.ssllabs.com/ssltest/analyze.html?d=omnipathdb.org

Overall, I can recommend to find out where is the root certificate store on your computer that your Python client uses, and how it is maintained. Then update it or add manually the *ISGR Root X1* certificate. E.g. `decoupler` uses the `omnipath` Python module, that is built on the `requests` module, which uses `libcurl` in its core, and this `libcurl` gets the certificates from a certain directory, probably managed by your operating system, or some other software like anaconda. *ISGR Root X1* has been published in 2015, hence your certificate store might be really old. This certificate is indeed signed by itself, but it is a root certificate, that means it should be ultimately trusted.

Best,

Denes

**Comment by joseph-siefert** [comment]
Solved on our end. Thanks
