### ISSUE TITLE
Are there missing pathways in REACTOME?

### ISSUE THREAD

**Issue by Nusob888** [saezlab/decoupler-py#23]
Hi, 

Thanks for the great resource. 
I am transitioning my workflows to python based tools and decoupler is great. However, I am getting a few discrepant results from my analysis in R using XGR. 

The main reason appears to be a few pathways are missing in the 'reactome_pathways' collection in decoupler. An example is Translocation_of_ZAP-70_at_immunological_synapse. 

I was just wondering if these databases were pre-trimmed down?

Many thanks

**Comment by Nusob888** [comment]
Hi @PauBadiaM,

Thanks for your reply! I think I have narrowed it down now. It appears those pathways have been concatenated into higher order pathways around 2014'ish, the one in question now falls under a larger pathway of PD1-signaling. It appears XGR has not updated its Msigdb, or perhaps it is purposefully pulling sub-pathways as it considers hierarchy of terms. 

It would be great to use these finer detailed pathways, but I am not sure how or whether that remains robust.

**Comment by PauBadiaM** [comment]
Hi @Nusob888,

Oh I see! It could be the case that they use a fixed version of MSigDB. Regarding the reliability of the subpathways, I would check if there is information somewhere in the [release notes](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Release_Notes) justifying this change, just in case. Hope this is helpful!
