### ISSUE TITLE
We can not download PROGENy database in decouplerpy.

### ISSUE THREAD

**Issue by DBinary** [saezlab/decoupler-py#28]
Dear authors:
When I tried to used this function to download the PROGENy Database, for example:
```
model = dc.get_progeny(organism='human', top=100)
model
```
It was wrong and the error is here:
```
RetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?format=tsv&resources=PROGENy (Caused by ResponseError('too many 500 error responses'))
```

**Comment by PauBadiaM** [comment]
Hi @DBinary 

Thanks for opening this issue. It seems like the OmniPath server is down. @deeenes, could you take a look please?

**Comment by deeenes** [comment]
@DBinary  Thanks for reporting, and apologies for the inconvenience. Should be working again now.

**Comment by DBinary** [comment]
Thank you so much, the error has been fixed!
