### ISSUE TITLE
PanglaoDB tutorial doesn't work

### ISSUE THREAD

**Issue by Intron7** [saezlab/decoupler-py#3]
Dear Decoupler Team,
I was excited to use the method in the notebook `Cell type annotation from marker genes` on my data. However it didn't work. I got the following error.
`PanglaoDB is not a valid resource. Please, run decoupler.show_resources to see the list of available resources.`
On the Omnipath website it still lists PanglaoDB. I have the newest pypi - versions of Omnipath and Decoupler installed

**Comment by PauBadiaM** [comment]
Hi @Intron7 
Thanks for checking the packages! Currently there is a problem with OmniPath, somehow `PanglaoDB` is missing, we are working on solving it. I'll let you know once it works!

**Comment by PauBadiaM** [comment]
Apparently there was an error building the latest version of OmniPath. The server will get updated over the weekend, sorry for the inconvenience! I will close this issue once it's updated.

**Comment by PauBadiaM** [comment]
Hi @Intron7,

The issue with the OmniPath server has been fixed. Just in case, remove the previous cache by running `rm $HOME/.cache/omnipathdb/*`, and then try:

```python
import decoupler as dc

markers = dc.get_resource('PanglaoDB')
markers
```

It should work now.
