### ISSUE TITLE
Is there any plan or ongoing work to add decoupler-py to conda-forge or bioconda?

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#36]
Hi, it would greatly facilitate this package from workflow environments and other setups if decoupler-py could be added to conda-forge or bioconda, depending on where its dependencies are. Thanks!

**Comment by PauBadiaM** [comment]
Hi @pcm32 

Indeed it would be quite helpful to have it in `conda-forge`. This is something I started looking a while ago but didn't have time to implement. Once I finish this release I'll look how to do it ;)

**Comment by PauBadiaM** [comment]
Thanks to @pcm32 solved in 5babf3db1e8cdf73cfadecc89613970b5462405e
