### ISSUE TITLE
plot_psbulk_samples does not exist

### ISSUE THREAD

**Issue by TheBorgy** [saezlab/decoupler-py#39]
**Describe the bug**
module 'decoupler' has no attribute 'plot_psbulk_samples' though it is part of the package

**To Reproduce**
run your pipeline using the latest decoupler installation

Please provide exact steps to reproduce the bug in a clean Python environment. In case it's not clear what's causing this bug, please provide the data or the data generation procedure.
Your own data

**Expected behavior**
plot as provided in pipeline

**System**
Google Colab
**Additional context**
NA

**Comment by PauBadiaM** [comment]
Hi @TheBorgy,

This is because I'm still working on finishing this release, so it is not yet in PyPI. However, you can install the latest version from GitHub directly using this command so that you can use `plot_psbulk_samples`:
```
pip install git+https://github.com/saezlab/decoupler-py
```
Hope this is helpful.
