### ISSUE TITLE
run_ora

### ISSUE THREAD

**Issue by elektrafying2000** [saezlab/decoupler-py#43]
I was also wondering in the run_ora function how the top 5% of most expressed genes is chosen! Thanks again

**Comment by PauBadiaM** [comment]
Hi @elektrafying2000,

`ora`([docs](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.run_ora.html#decoupler.run_ora)) works by first sorting the genes of each cell based on their gene expression values and selecting an arbitrary amount of top expressed genes. By default it is the top 5%, meaning that if you have 100 genes in your `mat` you select only the top expressed 5 genes per cell, but this value can be set manually to be any number (`n_up`). The function also allows to select bottom genes (`n_bottom`) in cause you are working with gene contrast statistics obtained after DEG. In the end, you have a collection of genes per cell, that will be tested for over-representation using a one tailed fisher exact test against the gene sets stored in the database of your choice. `ora` also has a version that allows to run enrichment just by a list of genes with `get_ora_df`([docs](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.get_ora_df.html#decoupler.get_ora_df)), for when you don't have gene level statistics available to do the sorting.

Hope this is clear, please let me know if you have more questions.
