### ISSUE TITLE
rank_sources_groups

### ISSUE THREAD

**Issue by cdiaz45** [saezlab/decoupler-py#49]
Thank you in advance for taking the time to look at this and also for a great tool. 

**Describe the bug**

**To Reproduce**
Hello I am going through the steps here to annotate my own data. The steps up to there are exactly the same as in the tutorial.

https://decoupler-py.readthedocs.io/en/latest/notebooks/cell_annotation.html

And I run into issues with the following line:
df = dc.rank_sources_groups(acts, groupby='leiden', reference='rest', method='t-test_overestim_var')

Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 df = dc.rank_sources_groups(acts, groupby='leiden', reference='rest', method='t-test_overestim_var')
      2 df

AttributeError: module 'decoupler' has no attribute 'rank_sources_groups'

My version of decoupler is 1.4.0

Thank you again and sorry if it is very basic question. 
Carmen

**Comment by cdiaz45** [comment]
The only way around it I found was to manually copy/paste the function into the notebook (I changed the name to rank_groups), then do:
import pandas as pd
from decoupler import p_adjust_fdr
rank_groups(acts, groupby='leiden', reference='rest', method='t-test_overestim_var')

**Comment by PauBadiaM** [comment]
Hi @cdiaz45 

No problem! I checked and the function should be correctly imported from the current version, maybe you have a pre-release `1.4.0` version installed from GitHub. I would try to uninstall decoupler and install it again:
```
pip uninstall decoupler
```
```
pip install decoupler==1.4.0
```
Then restart the kernel and try again. Also just in case check that you are using the correct python environment/kernel when running the script/notebook.
Hope this is helpful! Let me know if it worked

**Comment by cdiaz45** [comment]
Thank you!!!
