### ISSUE TITLE
Weird reindexing

### ISSUE THREAD

**Issue by ACheccoli** [saezlab/decoupler-py#50]
Hello there, 
thank you very much for sharing **decoupler-py** and my compliments for this tool.

I am following the tutorial on Bulk functional analysis and I didn't have any problems until when I ran the following:

```python
dc.plot_targets(results_df,stat='stat', source_name='Jund',net=collectri,top=15)
```

I am receiving this error message :
```
_InvalidIndexError: Reindexing only valid with uniquely valued Index objects

File ~/miniconda3/envs/pydeseq2/lib/python3.10/site-packages/decoupler/plotting.py:338, in plot_targets(data, stat, source_name, net, source, target, weight, top, figsize, dpi, ax, return_fig, save)
    335 w = net[net[source] == source_name].set_index(target)[[weight]]
    337 # Join
--> 338 data = pd.concat([data, w], axis=1, join='inner')
    340 # Define activation/inhibition color
    341 pos = ((data[weight] >= 0) & (data[stat] >= 0)) | ((data[weight] < 0) & (data[stat] < 0))_
```

Is there a way to deal with duplicated indexes and preserve the multiplicity of TF's targets? 

I set up the conda env by using the latest git repo.

**Comment by PauBadiaM** [comment]
Hi @ACheccoli ,

Huh, this is weird, it seems you have duplicated TF-Gene entries in the `collectri` network. Did you modify it somehow? The output of `dc.get_collectri` should return unique TF-Gene interactions, even when performing orthology conversion to other organisms.
To solve it you could try to remove those duplicates by running:
```python
collectri = collectri.drop_duplicates(['source', 'target'])
```
Then it should work.

By the way, it is still experimental and I still haven't updated the vignettes, but if you install the latest version of decoupler from GitHub (`pip install git+https://github.com/saezlab/decoupler-py`), you can plot and obtain the leading edge of the target genes, here an example:
```python
fig, le = dc.plot_running_score(
    df=results_df.reset_index(),
    names='GeneName',
    values='stat',
    net=collectri,
    set_name='JUND',
    source='source',
    target='target',
    figsize=(5, 5),
    dpi=100
)
le
```
```
array(['IL11', 'JUNB', 'NGF', 'ITGB3', 'TGFB1', 'MAPK8', 'PTGS2', 'EGF',
       'SERPINE1', 'CDK2', 'IL6'], dtype='<U28')
```
![image](https://github.com/saezlab/decoupler-py/assets/44896790/15491d53-7f97-4722-a960-2dc29984158c)
Just in case you are interested.
Hope this is helpful!

**Comment by ACheccoli** [comment]
Hi Pau, thanks for reaching out.
I didn't modified collectri after its creation. 
I tried to drop duplicates but the error persist:



dc.plot_targets(results_df, stat='stat', source_name='Jund', net=collectri, top=15)

---------------------------------------------------------------------------
InvalidIndexError                         Traceback (most recent call last)
Cell In[30], line 1
----> 1 dc.plot_targets(results_df, stat='stat', source_name='Jund', net=collectri, top=15)

File ~/miniconda3/envs/pydeseq2/lib/python3.10/site-packages/decoupler/plotting.py:338, in plot_targets(data, stat, source_name, net, source, target, weight, top, figsize, dpi, ax, return_fig, save)
    335 w = net[net[source] == source_name].set_index(target)[[weight]]
    337 # Join
--> 338 data = pd.concat([data, w], axis=1, join='inner')
    340 # Define activation/inhibition color
    341 pos = ((data[weight] >= 0) & (data[stat] >= 0)) | ((data[weight] < 0) & (data[stat] < 0))

File ~/miniconda3/envs/pydeseq2/lib/python3.10/site-packages/pandas/core/reshape/concat.py:385, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    370     copy = False
    372 op = _Concatenator(
    373     objs,
    374     axis=axis,
   (...)
    382     sort=sort,
    383 )
--> 385 return op.get_result()

File ~/miniconda3/envs/pydeseq2/lib/python3.10/site-packages/pandas/core/reshape/concat.py:612, in _Concatenator.get_result(self)
    610         obj_labels = obj.axes[1 - ax]
    611         if not new_labels.equals(obj_labels):
--> 612             indexers[ax] = obj_labels.get_indexer(new_labels)
    614     mgrs_indexers.append((obj._mgr, indexers))
    616 new_data = concatenate_managers(
    617     mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    618 )

File ~/miniconda3/envs/pydeseq2/lib/python3.10/site-packages/pandas/core/indexes/base.py:3731, in Index.get_indexer(self, target, method, limit, tolerance)
   3728 self._check_indexing_method(method, limit, tolerance)
   3730 if not self._index_as_unique:
-> 3731     raise InvalidIndexError(self._requires_unique_msg)
   3733 if len(target) == 0:
   3734     return np.array([], dtype=np.intp)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects



Thanks for sharing the enrichment score script btw!

**Comment by PauBadiaM** [comment]
Hi @ACheccoli 

No problem! Could you paste how do you run `dc.get_collectri`? With which parameters, etc. I see that you specify "Jund" so I guess you are working with `organism="mouse"`. If possible, could you also show the head (~5 rows) of your `results_df`? And finally, could you tell me which `pandas` version you are using? You can check this by running:
```python
import pandas as pd
pd.__version__
```

**Comment by ACheccoli** [comment]
This is the preview of first 5 lines of results_df:

![Screenshot 2023-06-20 at 16-05-02 decoupler_ICD_core - Jupyter Notebook](https://github.com/saezlab/decoupler-py/assets/66956232/369731fa-25bd-47ca-a889-684780dbd128)

import pandas as pd
pd.__version__

gives me back: '2.0.2'

regarding collectri creation:


![image](https://github.com/saezlab/decoupler-py/assets/66956232/f8e70306-63ef-487a-b36c-2bb33084962e)

thanks a lot.
Best,
Andrea

**Comment by ACheccoli** [comment]
It worked perfectly. Thank you very much
