### ISSUE TITLE
run_ora using adata as the input

### ISSUE THREAD

**Issue by biopzhang** [saezlab/decoupler-py#56]
**Describe the bug**
Using adata as input, if there is an empty sample (i.e., expression of the cell/sample is 0 for all genes), there will be an error writing the results to adata.obsm due to the deletion of the empty sample(s). 

dc.run_ora(
    mat=adata,
    net=msigdb,
    source='geneset',
    target='genesymbol',
    verbose=True,
    use_raw=False
)

**To Reproduce**
As described above.

**Expected behavior**
As described above.

**System**
 - OS: [e.g. macOS Ventura]
 - Python version [e.g. 3.9]

**Additional context**
By any means, an empty sample should not be present in the data. However, as decoupler actively check for empty samples and genes and deletes them, for integrity, it might be reasonable to return the repaired adata with results.

**Comment by PauBadiaM** [comment]
Hi @biopzhang ,

Thanks for finding this out! Indeed it should, but its going to be hard to refactor the code to accommodate this. I'll keep it in mind but for now it's on low priority since it is an edge case and the user can always remove those cells beforehand.

**Comment by biopzhang** [comment]
> Hi @biopzhang ,
> 
> Thanks for finding this out! Indeed it should, but its going to be hard to refactor the code to accommodate this. I'll keep it in mind but for now it's on low priority since it is an edge case and the user can always remove those cells beforehand.

Sounds reasonable to me. Thanks!

**Comment by PauBadiaM** [comment]
Fixed in 20922198a04cac8dc4511e1e110a050ecfadcc66
