### ISSUE TITLE
Regarding the function 'get_metadata_association'

### ISSUE THREAD

**Issue by Phil-Momoka** [saezlab/decoupler-py#59]
Hi,

I am new to decoupler and am now trying to go through the tutorial of pseudobulk analysis. However, I encountered a problem at step 12 where the tutorial code looks like this:
`dc.get_metadata_associations(pp_pdata,`
`obs_keys = ['sex', 'disease', 'cell_type', 'psbulk_n_cells', 'psbulk_counts'], `
`obsm_key='X_pca', #where the PCs are stored`
`uns_key='pca_anova', #where the results are stored`
`inplace=True)`

And it returned with the error
`AttributeError: module 'decoupler' has no attribute 'get_metadata_associations'`

I am using ver 1.4.0 of decoupler.

I searched the doc but it seems to me that we really don't have a function named `get_metadata_associations`. This maybe a dumb question but what shall I do to correct the code? Is the function obsolete?

**Comment by demian1** [comment]
Hi @Phil-Momoka
This function was added just last week and is therefore only available through GitHub for now.
You can update to the version on GitHub with `pip install git+https://github.com/saezlab/decoupler-py.git`
Be aware that the association is made with ANOVA using the statsmodels package that you need to install as well.

**Comment by Phil-Momoka** [comment]
Hi @demian1 
Thank you for your quick response! I will try using the newest version.

**Comment by ssun1116** [comment]
Hello, I'm also interested in using the `get_metadata_associations` function. It has been working well for me so far. However, I encountered a TypeError when attempting to use the `dc.plot_associations code`. 
I would greatly appreciate it if you could help me resolve this issue.
Thank you in advance!

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[14], line 2
      1 plt.figure(figsize=(7,10))
----> 2 ax, legend_axes = dc.plot_associations(pp_pdata,
      3                                        uns_key='pca_anova', #summary statistics from the anova tests
      4                                        obsm_key='X_pca', #where the PCs are stored
      5                                        stat_col='p_adj', #which summary statistic to plot
      6                                        obs_annotation_cols = ['condition', 'cluster_original'],
      7                                        titles=['Adjusted p-values from ANOVA', 'Principle component scores']) # which sample annotations to plot
      8 plt.show()

File ~/.conda/envs/BrainAtlas/lib/python3.8/site-packages/decoupler/plotting.py:1590, in plot_associations(data, uns_key, associations, cols, obs_annotation_cols, obsm_key, use_X, layer, stat_col, titles, scores_kwargs, stats_kwargs)
   1587 cm_stats = pch.ClusterMapPlotter(data=stats, plot=False, **stats_defaults)
   1589 #combine clustermaps vertically
-> 1590 ax, legend_axes = pch.composite(cmlist = [cm_stats, cm_scores], main = 1, axis = 0, height_ratios=[1,3], row_gap=7, legend_gap=15)
   1592 #add titles
   1593 if titles is not None:

TypeError: composite() got an unexpected keyword argument 'height_ratios'
```

**Comment by demian1** [comment]
Hi @ssun1116
In order to fix this issue, I would recommend to update to the latest version of PyComplexHeatmap (at least commit ac50aca) from GitHub
`pip install git+https://github.com/DingWB/PyComplexHeatmap`
