### ISSUE TITLE
Check other options besides csr_matrix in check_X inside get_pseudobulk

### ISSUE THREAD

**Issue by roramirezf** [saezlab/decoupler-py#61]
**Describe the bug**
Some anndata objects contain in .X another scipy sparse matrices such as csc (compressed sparse column) which cause an error from the `np.isfinite` function in `check_X(X, mode=mode, skip_checks=skip_checks)` that can't be skipped in `get_pseudobulk`.

**To Reproduce**
In your pseudobulk vignette for example do:
`adata.layers['counts']  = adata.X.tocsc(copy = True)`

Then just run the pseudobulk function and you will get the error 

**Expected behavior**
I recommend either expanding the checks with `isinstance(sc_dat.X, csc_matrix)` or explicitly mention that you expect csr_matrix

**Comment by PauBadiaM** [comment]
Thanks for finding this @roramirezf ! May I ask in which instances do you work with `csc` format?
I think I will explicitly mention that we expect `csr_matrix`

**Comment by roramirezf** [comment]
`csc` is something that I observed from data transformations of Seurat objects to anndata via `Zellconverter`

Seurat -> SinglecellExperiment -> anndata

**Comment by PauBadiaM** [comment]
Ahh I see! Makes sense since it is coming from a (gene, obs) matrix, but it's an inefficient format for the final form of (obs, gene). But this is something that should be handled by `zellkonverter`. Mhm, I'll figure how to handle this.

**Comment by PauBadiaM** [comment]
Solved in 7752273722a434b83b72c206ff36d6ec5b4df18d
