### ISSUE TITLE
Editing plots using matplotlib

### ISSUE THREAD

**Issue by alpha-1-centauri** [saezlab/decoupler-py#63]
Is there a way of editing plots using matplotlib pyplot (e.g. by specificying a predetermined axis for a figure)?

**Comment by alpha-1-centauri** [comment]
Worked great - thank you for the quick reply!

**Comment by TKMarkCheng** [comment]
To follow up on this, at the moment the matplotlib based plots e.g. plot_dotplot() is not working as well. Is it something to do with how plot_filter_by_expr uses seaborn whilst plot_dotplot uses matplotlib.axes.scatter() ?

for example:

```python
import decoupler as dc
import matplotlib.pyplot as plt
# Read 
mat, net = dc.get_toy_data()

# Cerate a new figure
fig, ax = plt.subplots(1, 3)
ax = ax.ravel()

# Add plot in first subplot
dc.plot_filter_by_expr(mat, ax=ax[0])
# Add plot in second subplot, also works
dc.plot_filter_by_expr(mat, ax=ax[1])

# add plot in third subplot, this breaks down and is not plotted in the same figure.
dc.plot_dotplot(
    net,
    x='weight',y='source',
    s='weight',c='weight',
    scale=0.5,title="dotplot",
    figsize=(3, 6),
    ax=ax[2]
)
```
![image](https://github.com/user-attachments/assets/9c3c5cf9-fb7d-491e-b5fa-270264bd1866)
![image](https://github.com/user-attachments/assets/9bdb6188-6837-41bf-b8a5-8d13f99e9c08)
