### ISSUE TITLE
Include unique identifiers for GO terms?

### ISSUE THREAD

**Issue by brainfo** [saezlab/decoupler-py#66]
For the MSigDB resources you provided, e.g., 
in go_bp, the geneset information only includes human-readable term names but no IDs, then could it be more replicable and better compatible with other downstream analyses on those terms if you include the IDs?

Best,
Hong

**Comment by brainfo** [comment]
OK, I see pypath, I should try importing the resources including IDs myself.

**Comment by PauBadiaM** [comment]
Hi @brainfo 

Are you referring to the gene set ids or to the gene ids? In any case, you can access those from `pypath` if I recall correctly.

**Comment by brainfo** [comment]
> Hi @brainfo
> 
> Are you referring to the gene set ids or to the gene ids? In any case, you can access those from `pypath` if I recall correctly.

Hi, I mean GO term IDs. like GO: 7 digits
