### ISSUE TITLE
Clipping of `min_counts` in `get_pseudobulk`

### ISSUE THREAD

**Issue by Claptar** [saezlab/decoupler-py#73]
Hello!

I'm currently working with Visium data of prefrontal cortex from different species. And I want to make pseudobulks for each of the species, analyse them sepparatly and then merge them together. The problem I encoutered is that I can't set `min_counts` parameter to zero (because it is [clipped ](https://github.com/saezlab/decoupler-py/blob/a2b4f45c9d9d2b2aa6fe6a621e62ccf3b5f4946d/decoupler/utils_anndata.py#L348)later in the function to 1) and get some of the genes filtered. So when I merge different species after this I get less genes than I expect.

Example of code (calculate pseudobulk first, merge adata after):
```
mode = 'mean'
for file_name in tqdm(os.listdir(dir_path)):
    file = file_name.split('.')[0]
    # read visium data
    adata = sc.read_h5ad(dir_path + file_name)
    adata.obs_names_make_unique()
    adata.obs.label.replace({"L6a": "L6", "L6b": "L6"}, inplace=True)
    # calculate pseudobulks
    pdata = dc.get_pseudobulk(
    adata,
    sample_col='sample_id',
    groups_col='label',
    mode=mode,
    min_cells=0,
    min_counts=0
    )

adata_pb = an.concat([pb_dict['human'], pb_dict['chimp'], pb_dict['macaque']], merge='same')
adata_pb


>>>AnnData object with n_obs × n_vars = 94 × 13086
    obs: 'layer', 'sample_id', 'psbulk_n_cells', 'psbulk_counts', 'condition'
    var: 'feature_types', 'mt', 'hb', 'ribo'
    layers: 'psbulk_props'
```

Example of code (merge adata first, calculate pseudobulk after):
```
human = sc.read_h5ad(dir_path + 'human.h5ad')
chimp = sc.read_h5ad(dir_path + 'chimp.h5ad')
macaque = sc.read_h5ad(dir_path + 'macaque.h5ad')

# Concat adata objects
adata = an.concat([human, chimp, macaque] , merge='same',uns_merge="unique")
adata.obs.label.replace({"L6a": "L6", "L6b": "L6"}, inplace=True)

# Make pseudobulk
pdata = dc.get_pseudobulk(
    adata,
    sample_col='sample_id',
    groups_col='label',
    mode=mode,
    min_cells=0,
    min_counts=0
    )

pdata

AnnData object with n_obs × n_vars = 94 × 14963
    obs: 'in_tissue', 'label', 'sample_id', 'psbulk_n_cells', 'psbulk_counts'
    var: 'feature_types', 'mt', 'hb', 'ribo'
    layers: 'psbulk_props'
```

**Comment by PauBadiaM** [comment]
Hi @Claptar,

Ah I see. Yes, `get_pseudobulk` removes empty genes. My question is then, in which context would you want to keep genes that are completely empty?

**Comment by PauBadiaM** [comment]
Now it is possible to keep empty rows/columns with the param `remove_empty=False` added in feabe4ef24bcd99a2ffcf624ae416941a6342c9e
