### ISSUE TITLE
A recommendation for prior network preprocessing based on expression data

### ISSUE THREAD

**Issue by janursa** [saezlab/decoupler-py#75]
This isn't an issue with the decoupler itself but rather a recommendation regarding the documentation of [TF activity enrichment](https://github.com/saezlab/decoupler-py/blob/d5926b6c59116e6a82d140c8abe408fe7c96689e/docs/source/notebooks/dorothea.ipynb#L369). I noticed that you use ULM to estimate TF activities in [this line](https://github.com/saezlab/decoupler-py/blob/d5926b6c59116e6a82d140c8abe408fe7c96689e/docs/source/notebooks/dorothea.ipynb#L369). Before reaching this line, it might be beneficial to pre-process the prior network by filtering it to only include genes that are present in the 'adata' object.

In its current form, many genes in the network may not be found in the expression data, which could lead to less-informed TF activity estimates for those genes. By filtering the prior network to match the genes in 'adata', you can ensure that the TF activities are calculated with relevant and available expression data, resulting in more accurate and meaningful results. pls let me know if i am missing something here. thanks

**Comment by PauBadiaM** [comment]
Hi @janursa,

This filtering is done automatically under the hood by any of the methods in `decoupler`. We always prune the networks based on the gene universe provided by the `adata` object with the function [decoupler.filt_min_n](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.filt_min_n.html#decoupler.filt_min_n). Hope this is helpful!

**Comment by janursa** [comment]
@PauBadiaM, thank you for the support. I didn't check the content of `fit_min_n` but I can provide you with a reproducible example that shows that not all the TFs in `ulm_estimate` exist in `adata`.
```python
import decoupler as dc
import numpy as np
import scanpy as sc
import pandas as pd
adata = sc.datasets.pbmc3k_processed()
if False:
    prior_net = dc.get_collectri(organism='human', split_complexes=False)
    prior_net.to_csv(f'../outputs/prior_net.csv')
else:
    prior_net = pd.read_csv('../outputs/prior_net.csv', index_col=0)
dc.run_ulm(
        mat=adata,
        net=prior_net,
        source='source',
        target='target',
        weight='weight',
        verbose=True
    )
mrna_genes = adata.var.index.unique()
tfs = adata.obsm['ulm_estimate'].columns.unique()
tfs_in_mrna = np.intersect1d(tfs, mrna_genes)
print(f'{len(tfs)=} , {len(tfs_in_mrna)= }')
``` 
Pls let me know what i am missing.

**Comment by PauBadiaM** [comment]
Hi @janursa 
Ah I see what you mean now. Since TF expression happens in bursts, and transcriptomics is just a snapshot, it can be the case that it does not show expression, especially in single-cell data where there are many dropout effects. Therefore, even if a TF is shown not to be expressed it might still be interesting to compute its activity. [Here's](https://github.com/saezlab/CollecTRI/issues/8#issuecomment-1697295489) a more detailed reply to a similar question if you are interested. Personally I would keep them, but if needed one could just run:
```python
sources = net['source'].unique()
msk = np.isin(sources, adata.var_names)
msk = np.isin(net['sources'], sources[msk])
net = net[msk]
```

**Comment by janursa** [comment]
I completely agree that using transcriptomics as a proxy for protein levels is a significant simplification. In fact, my current research focus revolves around finding ways to circumvent this assumption in gene regulatory network (GRN) inference.

Returning to the issue at hand, when expression values are missing, how to calculate the t-value of the slope in ULM since it relies on having both expression values and GRN weights. I should note that my understanding of ULM is solely based on your documentation, where you've illustrated the calculation process.

**Comment by janursa** [comment]
@PauBadiaM, thank you for the clarification.

I've noticed the implementation of `filt_min_n`, where you remove links from `net` if their `target` is not present in `adata`. My earlier expectation was that links would be removed if their `source` is not part of `adata`, but I now understand that this isn't necessary. Everything is clear now. Thank you very much for your explanation, and I apologize for any earlier confusion.

**Comment by PauBadiaM** [comment]
No problem at all! Anything else comes up let me know ;)
