### ISSUE TITLE
How does run_aucell receive the gene signatures?

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#76]
I'm looking at the [run_aucell documentation](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.run_aucell.html#decoupler.run_aucell) but I'm struggling to see how you are supposed to pass the gene signature (or gene signatures list) that you want to score with AUCell. I see that after the AnnData, the function requires:

- network
- source
- target

How do I use those to encode a geneset to pass it to the function? Could you give an example? Should this be a dataframe where in one of the columns I have a geneset names (source) and in the other gene_ids (targets) compatible with the var.index of the passed AnnData? Then obsm gets a matrix with columns for each of the genesets?

Thanks!

**Comment by PauBadiaM** [comment]
Hi @pcm32 ,

To pass any gene set you need to format them into a long format data-frame like this one:
![image](https://github.com/saezlab/decoupler-py/assets/44896790/5c5d2d95-0b30-4387-b5fc-6a3976fc4435)

The to `aucell` you only need to specify the names of the columns of `net` like this:
```python
dc.run_aucell(
    mat=mat,
    net=net,
    source='geneset',
    target='genesymbol'
)
```
Note that the only important columns in the end are `geneset` and `genesymbol`.

Just in case it is useful for you, the is the function `decoupler.read_gmt` which reads `gmt` files into this long format already. 
> Then obsm gets a matrix with columns for each of the genesets?

Yes, for each unique element in the `source` column of your `net` you will have a column in the resulting `.obsm`. 

Hope this is helpful!
