### ISSUE TITLE
Using decoupler to implement Cytosig analysis

### ISSUE THREAD

**Issue by SNOL2** [saezlab/decoupler-py#77]
Hi, thanks for this wonderful tool!
I was wondering if there is a tutorial for using decoupler to implement Cytosig analysis.
Thanks again!

**Comment by deeenes** [comment]
Hi,

You can follow the exact same procedure as for [pathway activity inference](https://decoupler-py.readthedocs.io/en/latest/notebooks/progeny.html#PROGENy-model). Instead of PROGENy, simply use CytoSig:

```
import decoupler as dc

cytosig = dc.get_resource('CytoSig')

dc.run_mlm(
    mat = adata,  # <- your single cell data
    net = cytosig,
    verbose = True,
)

adata.obsm['mlm_estimate']  # <- the results
```

**Comment by SNOL2** [comment]
> Hi,
> 
> You can follow the exact same procedure as for [pathway activity inference](https://decoupler-py.readthedocs.io/en/latest/notebooks/progeny.html#PROGENy-model). Instead of PROGENy, simply use CytoSig:
> 
> ```
> import decoupler as dc
> 
> cytosig = dc.get_resource('CytoSig')
> 
> dc.run_mlm(
>     mat = adata,  # <- your single cell data
>     net = cytosig,
>     verbose = True,
> )
> 
> adata.obsm['mlm_estimate']  # <- the results
> ```

Got it! Thanks!
