### ISSUE TITLE
get_metadata_associations - TypeError: data type 'category' not understood

### ISSUE THREAD

**Issue by ttszen** [saezlab/decoupler-py#78]
Hello! Thank you for the really useful tool. I was trying to run `get_metadata_associations` on my pseudo-bulked data. 

I unfortunately run into the this, error called `TypeError: data type 'category' not understood` when running the following line of code. This issue disappears when I remove psbulk_counts and psbulk_n_cells. I have checked datatypes for the obs_keys and they seem to be supported by the function as they are either a category or float. 

Do you have any recommendations for this? 

```
dc.get_metadata_associations(
    pp_pdata,
    obs_keys = ['sample_name', 'phase', 'psbulk_counts', 'psbulk_n_cells'], #metadata columns to associate to PCs
    obsm_key='X_pca',  # where the PCs are stored
    uns_key='pca_anova',  # where the results are stored
    inplace=True
)
```

It'd be great to get your thoughts and happy to discuss more.

**Comment by PauBadiaM** [comment]
Hi @ttszen,

Thanks for raising this issue. I guess this is `pandas` doing some weird type transformation for some of the columns. Could you confirm if `psbulk_counts` and `psbulk_counts` are stored as `float`s? Else, @demian1, what do you think could be the issue here?

**Comment by ttszen** [comment]
Hi @PauBadiaM, thanks for getting back to me. Yes, it appears that these two columns are stored as `float`. Please see the attached screenshot. Let me know if there is any other information you require. 
![Screenshot 2023-09-18 at 09 14 35](https://github.com/saezlab/decoupler-py/assets/89928200/0f1618e1-3f86-411e-a568-bc9798d1594e)

**Comment by deeenes** [comment]
Hi @ttszen, I afraid it's very difficult to find the reason without a complete traceback. Also, it would be fantastic if you could confirm that all the major involved packages are up to date: `pandas`, `anndata` and `decoupler`.

**Comment by demian1** [comment]
Hi @ttszen could you please provide a minimal example to reproduce the error ?

**Comment by ttszen** [comment]
Hi @deeenes and @demian1. Thank you for getting back to me. I just wanted to leave a note saying I haven't forgotten this; I've been having an intense couple of weeks of lab experiments and away at a conference for most of this week. 

I will get back to you both as soon as I'm back later this week.

**Comment by ttszen** [comment]
Hi @deeenes and @demian1. Apologies again for the delay. Below are the versions of the relevant packages I've used to reproduce the error. I've performed the analysis using the exact lines of code (until block 12) in the psedobulk tutorial on the website: [https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html) 

`pandas 1.2.3`           
`anndata 0.7.5`          
`scanpy 1.7.1`
`decoupler 1.5.0`

Hope that is helpful to reproduce the error but please let me know if you need further information.

**Comment by demian1** [comment]
Could you please try to update to a newer version of anndata (0.8.0) and scanpy (1.9) ?

From your questions it is also not exactly clear whether you are using the same data as in the vignette, or your own. If you are using your own data, then it is most likely that the columns of `.obs` you are using are in the wrong data format. Providing a minimal example of the data you are getting errors with, would be helpful in order to track down what the issue is.
