### ISSUE TITLE
Module request: UCell signatures

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#82]
Hi there, thanks again for this great package. Have you considered including the UCell cell signature to decoupler? Unfortunately only implemented in R: https://github.com/carmonalab/UCell/tree/master/R

Thanks!

**Comment by PauBadiaM** [comment]
Hi @pcm32 

Thank you for contributing ;) Regarding UCell, as far as I am aware, it is just a faster implementation of AUCell in R, which the one implemented in `decoupler` is already faster. Let me know if this is not the case and I'll consider adding it.

**Comment by pcm32** [comment]
Indeed, you are right, on closer inspection is mostly a speed and memory improvement for the R implementation. From the UCell paper:

> We note that the U statistic is closely related to the area-under-the-curve (AUC) statistic for ROC curves [[8]](https://www.sciencedirect.com/science/article/pii/S2001037021002816?via%3Dihub#b0040), therefore we expect UCell scores to correlate with methods based on AUC scores such as AUCell [[6]](https://www.sciencedirect.com/science/article/pii/S2001037021002816?via%3Dihub#b0030).
