### ISSUE TITLE
Switching to conda forge

### ISSUE THREAD

**Issue by wxicu** [saezlab/decoupler-py#84]
**Describe your question**
Hello everyone,
I saw decoupler is available with the bioconda channel, I would like to ask whether you'd be open to switching to conda forge, since most other scverse packages are on conda forge? Thank you!

Best regards
Xichen

**Comment by PauBadiaM** [comment]
Hi @wxicu,

I agree, the problem is that it is already in bioconda. Do you know what would be the best course of action? I will try to do a pull request in conda-forge but I don't know if it's going to work out.

**Comment by PauBadiaM** [comment]
I also tag @pcm32 here since he is the contact person for the bioconda upload

**Comment by pcm32** [comment]
A few things I would observe:

- currently bioconda generates a container, which is probably the most reproducible way of using the package. But containers can be generated on request for when the package moves.
- I would make sure that versions don't collide (so start with the conda forge version on the next version and make sure the bioconda auto-bump doesn't kick in).
- I'm not sure about what name we used in bioconda, but perhaps a slightly different name (like decoupler-py for instance if the other one is decoupler) might ensure there are no issues for the conda solvers. It might be irrelevant, but I'm not sure and maybe best to err on the side of caution.

**Comment by Zethson** [comment]
We also moved from bioconda to conda-forge for scanpy and it can sometimes happen that people install the old bioconda package. We did not find a better way of doing this.

I like the automatic container building of bioconda but people rarely use our tools as standalone containers I guess (there are use-cases though!)

**Comment by PauBadiaM** [comment]
Hi @Zethson, no problem! Just opened a PR in `conda-forge`, let's see how it goes: https://github.com/conda-forge/staged-recipes/pull/24595

**Comment by PauBadiaM** [comment]
@Zethson it took a while but finally it got accepted to conda-forge:
```
mamba create -n=decoupler conda-forge::decoupler-py
```
