### ISSUE TITLE
Problems running decoupleR with Compressed Sparse Column (csc) count matrix

### ISSUE THREAD

**Issue by vckraemer** [saezlab/decoupler-py#85]
Hello, 

I am running decoupleR on a scRNA-seq AnnData object and am running into issues since I updated decoupleR to version 1.5.0. 

I am running this function:

```python
import decoupler as dc

dc.run_ulm(
    mat=ann_data,
    net=reg,
    source='source',
    target='target',
    weight='weight',
    verbose=True,
    use_raw=False
)
``` 
and I am getting this error traceback: 
```
File "/lib/python3.11/site-packages/decoupler/method_ulm.py", line 105, in run_ulm
    m, r, c = extract(mat, use_raw=use_raw, verbose=verbose)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/decoupler/pre.py", line 94, in extract
    m, r, c = check_mat(m, r, c, verbose=verbose)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/decoupler/pre.py", line 19, in check_mat
    msk_features = np.count_nonzero(m, axis=0) == 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/numpy/core/numeric.py", line 484, in count_nonzero
    a_bool = a.astype(np.bool_, copy=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence.
```

I noticed that in the check_mat function, you are checking if the parsed matrix is a csr matrix or another kind of matrix and use special cases accordingly. I checked my AnnData object and noticed I have the expression matrix saved as csc matrix, so I am guessing this is the issue here. In previous versions of decoupleR (1.3.5, 1.4.0) I never had any problems.

Would you consider also implementing a case for csc matrices in decoupleR?

(I am running it on a linux system with Python 3.11)

**Comment by PauBadiaM** [comment]
Hi @vckraemer ,

Thanks for opening this issue. Internally, `decoupler` needs to work with the `csr` sparse format. I have updated the code in my last commit a8b778e10ef21a2a62d4acca18d3fc8a4c469a7e so that any sparse format is accepted now, but internally it transforms it into `csr`.

If you do not want to update the package, you could always do:
```python
adata.X = adata.X.tocsr()
```
Else, here is how to install the latest version from GitHub:
```python
pip install git+https://github.com/saezlab/decoupler-py
```
Let me know how it goes, hope this is helpful!

**Comment by vckraemer** [comment]
Hi @PauBadiaM,

thank you very much for adding this sparse matrix handling into your package! I did use the conversion method you mentioned as a workaround before, but this solution helps a lot. 

I also tested the new version already and I don't have any issues anymore.
