### ISSUE TITLE
Error downlaoding progeny model for mouse species 

### ISSUE THREAD

**Issue by archanabhardwaj** [saezlab/decoupler-py#86]
Hello 

I am using decoupler and using it in python environment. I used following lines of code : 

_import decoupler as dc
progeny = dc.get_progeny(organism='mouse', top=500)_

But it stops working until certain period : 

File ~/.conda/envs/liana/lib/python3.9/site-packages/requests/models.py:818, in Response.iter_content.<locals>.generate()
    816     yield from self.raw.stream(chunk_size, decode_content=True)
    817 except ProtocolError as e:
--> 818     raise ChunkedEncodingError(e)
    819 except DecodeError as e:
    820     raise ContentDecodingError(e)

ChunkedEncodingError: ('Connection broken: IncompleteRead(3731 bytes read, 4465 more expected)', IncompleteRead(3731 bytes read, 4465 more expected))

It would be great if you can help me to fix this issue. 

Thanks in advance

**Comment by deeenes** [comment]
The network transfer was unexpectedly interrupted. Have you tried it already a few times? Have you tried from a different network?

**Comment by archanabhardwaj** [comment]
Hello
I am running it in HPC cluster. I will contact IT person to fix it. 

As an alternative option, I am running same code on my local computer with all libraries installed. I have cell composition values for spatial transcriptome data (from cell2location results) for mouse species. To explore further, I am trying to run liana+ method https://liana-py.readthedocs.io/en/latest/notebooks/misty.html#Environment

As an essential option, trying to download pathway profile for mouse species. Pathway profiles works without error for human species. 

progeny = dc.get_progeny(organism='human', top=500)

![image](https://github.com/saezlab/decoupler-py/assets/15521523/a91ce5f2-74ff-4d38-8982-291bc623c133)


But switching to mouse species, gives me another error : 

![image](https://github.com/saezlab/decoupler-py/assets/15521523/e513f3de-65b8-403f-82bb-d953c0c24e3d)

I have latest version of omipath installed. But getting above error. 

All suggestions would be appreciated !!

**Comment by deeenes** [comment]
The error says the `pypath-omnipath` module is not installed, but in fact it can be also any error on its import. This module is required for mouse data as we do orthology translation on human data. From the trace we can see the `decoupler-py` is not up-to-date. I'd recommend to address this first: make sure all modules are their latest versions from git:

```
pip install --upgrade git+https://github.com/saezlab/decoupler-py.git
pip install --upgrade git+https://github.com/saezlab/omnipath.git
pip install --upgrade git+https://github.com/saezlab/pypath.git
```

We've recently done a number of developments especially to make database access more reliable, which will either solve your issue, or will provide more information, especially if you set the log level to low before trying again:

```
import logging
import decoupler as dc

logging.getLogger().setLevel(1)
p = dc.get_progeny(organism = 'mouse')
```
