### ISSUE TITLE
shuffle_net output not random

### ISSUE THREAD

**Issue by IBMB-MFP** [saezlab/decoupler-py#87]
Hi again - another behaviour that was unexpected (by me at least!) of shuffle_net.

Specifically, I would like to invoke shuffle_net repeatedly to do make a distribution of TF activities derived from random shuffled networks. So I called it repeatedly in a loop, like so:

```
for i in range(1, 1001):

    temp_net_shuffle = dc.shuffle_net(my_net, target = 'target', weight = 'weight').drop_duplicates(['source', 'target'])

    temp_mlm_results_shuffle = dc.run_mlm(mat = my_mat,
           net = temp_net_shuffle,
           verbose = True)

    temp_mlm_results_shuffle[0].to_csv(r'my_directory/shufflenet'+str(i)+'.txt', header = True, index = True, sep = '\t', mode = 'w')
```

What I expect is to then get 1000 different networks (and so 1000 different TF activity estimates from different shuffled networks). But it seems that every time I invoke shuffle_net on my network I get the same shuffled network out of it and so the same TF activities i.e. it's not really random.

Perhaps I have misunderstood this and it's not designed to be random? And I notice there is a 'seed' argument in the function - maybe I have to set a different seed each time (default is set to 42) ? But I don't quite understand the 'seed' argument. Is it indeed possible to have shuffle_net produce different random networks, and if so, how?

 - macOS Catalina 10.15.7
 - Python version 3.8.16
 - decoupler 1.4.0
 
Many thanks in advance,

Marcos

**Comment by PauBadiaM** [comment]
Hi @IBMB-MFP,

The `seed` argument fixes the obtained network, if you want to obtain different networks you can just change the seed at each iteration step `seed=i`. Hope this is helpful!
