### ISSUE TITLE
Pseudobulk for each sample

### ISSUE THREAD

**Issue by SNOL2** [saezlab/decoupler-py#89]
Hi,
Thanks for developing this wonderful tool!
I'd like to perform pseudobulk analyses for each sample, i.e. one expression vector for one sample. Considering the tumor purity, I suppose it is necessary to assign the weight to each cell type(especially malignant cells) when computing the sum of the counts. Could you please give me some advice?
Thanks again!

**Comment by PauBadiaM** [comment]
Hi @SNOL2

Thanks for using it! To perform pseudobulk at the sample level (not at the sample-cell type level) you can set the `groups_col` to `None` like this:
```python
pdata = dc.get_pseudobulk(
    adata=adata,
    sample_col='sample_id',  # Here your sample id column name
    groups_col=None,
    ...
)
```
The function `decoupler.get_pseudobulk` also accepts custom functions for the `mode` (which by default is `'sum'`). You could append your weight as a feature in `adata` and then write a custom function that takes this feature to do a weighted sum of your cells for example. Hope this is helpful!

**Comment by SNOL2** [comment]
I will give it a try. Thanks!
