### ISSUE TITLE
Get gene markers used to annotate the cell type

### ISSUE THREAD

**Issue by ryrl9703** [saezlab/decoupler-py#91]
```python
dc.run_ora(
    mat=adata,
    net=db,
    source='cell_type',
    target='genesymbol',
    min_n=3,
    verbose=True
)
```
When I finished dc.run_ora, I want  to get the gene markers that used to annotate the celltype, but the result of  dc.rank_sources_groups not contains the gene markers. Anyway can I get it?

**Comment by PauBadiaM** [comment]
Hi @ryrl9703,

The function `dc.run_ora` just returns the obtained -log10(p-value) of the one-tailed Fisher Exact Test per cell and gene set provided. If you want to explore which genes where the ones responsible for such an enrichment, I would recommend you to first generate a pseudobulk profile using [`dc.get_pseudobulk`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.get_pseudobulk.html#decoupler.get_pseudobulk) at the cell type level and then running the function [`dc.get_ora_df`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.get_ora_df.html#decoupler.get_ora_df) which returns more information such as which genes where overlapped between your mat and your gene set. Additionally, to visualize which genes might play a role you can use the function [`dc.plot_network`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.plot_network.html#decoupler.plot_network). Hope this is helpful!

**Comment by ryrl9703** [comment]
> Hi @ryrl9703,
> 
> The function `dc.run_ora` just returns the obtained -log10(p-value) of the one-tailed Fisher Exact Test per cell and gene set provided. If you want to explore which genes where the ones responsible for such an enrichment, I would recommend you to first generate a pseudobulk profile using [`dc.get_pseudobulk`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.get_pseudobulk.html#decoupler.get_pseudobulk) at the cell type level and then running the function [`dc.get_ora_df`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.get_ora_df.html#decoupler.get_ora_df) which returns more information such as which genes where overlapped between your mat and your gene set. Additionally, to visualize which genes might play a role you can use the function [`dc.plot_network`](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.plot_network.html#decoupler.plot_network). Hope this is helpful!

Okay, thank you. I will try it.
