### ISSUE TITLE
ValueError: Invalid value `loops` for `InteractionsQuery` in dc.get_collectri()

### ISSUE THREAD

**Issue by GERMAN00VP** [saezlab/decoupler-py#93]
I am following the decoupler tutorial for TF activity inference ( https://decoupler-py.readthedocs.io/en/latest/notebooks/dorothea.html ) and at the point where it is done:

 net = dc.get_collectri(organism='human', split_complexes=False)

I get the following error:

ValueError: Invalid value `loops` for `InteractionsQuery`. Valid options are: `['database', 'databases', 'dataset', 'datasets', 'directed', 'directeds', 'dorothea_level', 'dorothea_levels', 'dorothea_method', 'dorothea_methods', 'entity_type', 'entity_types', 'field', 'fields', 'format', 'formats', 'genesymbol', 'genesymbols', 'header', 'headers', 'license', 'licenses', 'limit', 'limits', 'organism', 'organisms', 'partner', 'partners', 'password', 'passwords', 'resource', 'resources', 'signed', 'signeds', 'source_target', 'source_targets', 'source', 'sources', 'target', 'targets', 'tfregulons_level', 'tfregulons_levels', 'tfregulons_method', 'tfregulons_methods', 'type', 'types']`.

How can I fix it?

Thank you,
Germán.

**Comment by deeenes** [comment]
Hi Germán,

This issue has been fixed around end of July, unfortunately we haven't updated the module in PyPI. We'll do it soon, until then installing from github is the solution:

```
pip install --upgrade 'git+https://github.com/saezlab/omnipath.git'
```

Once this is done, you'll likely encounter [another error](https://github.com/saezlab/decoupler-py/issues/92), which I plan to fix until tomorrow.

Best,
Denes

**Comment by GERMAN00VP** [comment]
That solved my error, thank you!
