### ISSUE TITLE
Announcement: some Galaxy modules for some decoupler functionalities

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#97]
Not really a question, but I thought I'd let you know that we have by now a couple of Decoupler functionalities in Galaxy modules (Pseudo-bulk and AUCell, but working on a couple more). I could make them available in usegalaxy.eu. We also have a complete Galaxy workflow for Pseudo-bulk based on that module, using EdgeR downstream and producing GSEAs and others.

We develop them here https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/tree/develop/tools/tertiary-analysis/decoupler

And available here for installation on any Galaxy instance: 
https://toolshed.g2.bx.psu.edu/repository/browse_repositories?f-free-text-search=decoupler&sort=name&operation=view_or_manage_repository&id=6c8288160438138d
https://toolshed.g2.bx.psu.edu/repository/browse_repositories?f-free-text-search=decoupler&sort=name&operation=view_or_manage_repository&id=b1b337fd21d9c731

Happy to add any required citations or others that we might have missed.

**Comment by PauBadiaM** [comment]
Oh wow, many thanks @pcm32 for taking the effort of implementing these into galaxy! :) 
Looks good to me, let me know if I can help in any way
