### ISSUE TITLE
Limiting usage of cores or threads

### ISSUE THREAD

**Issue by racng** [saezlab/decoupler-py#99]
Thank you for building this great tool!

I am using a machine with 256 cores. When I use `run_ora()`, the python process uses nearly all the cores (sometimes ~210 or ~230 cores). 
How do I control the number of cores/threads for this or other methods?

**Comment by PauBadiaM** [comment]
Hi @racng,

`decoupler` functions use the `numba` library under the hood to compile and optimize their code. To limit the usage of CPUs you can set the number of cores at the beginning of your script (to 32 for example).
```python
import numba as nb
nb.set_num_threads(n=32)

# Then run decoupler functions here
```
Hope this is helpful!

**Comment by racng** [comment]
Thank you @PauBadiaM ! I have tried what you suggested and it works 😄
